/**
 * APPLICATION — Model Doctor
 * A best-practice analyzer over the real model: finds measures that will render
 * badly (no format string), DAX that will scale badly (naked fact-table FILTER),
 * blank-unsafe division, and organisational gaps. Every finding says what's
 * wrong, why it matters, and — where it's safe — carries an automatic fix.
 */
import type { SemanticModel } from '@/domain/model'
import { parseDependencies } from './dependencies'

export type Severity = 'error' | 'warning' | 'info'

export interface Finding {
  id: string
  rule: string
  severity: Severity
  table: string
  measure: string
  message: string
  why: string
  /** A safe, mechanical fix we can apply (format/folder). */
  fix?: { formatString?: string; displayFolder?: string }
  /** A suggested DAX rewrite — shown for review, never auto-applied. */
  suggestedDax?: string
}

const DEFAULT_FORMAT = '#,0.00'

/** True when a measure plainly returns text, so no numeric format applies to it.
 * Deliberately narrow: a missed text measure costs one noisy finding, but a false
 * positive here would tell the user to format a real number as nothing. */
export function returnsText(dax: string): boolean {
  // Only the RETURN clause decides the type; a VAR block may hold anything.
  const ret = /\bRETURN\b([\s\S]*)$/i.exec(dax)
  const body = (ret ? ret[1] : dax).trim()
  if (body.startsWith('"')) return true // "Performance: " & …
  if (/^FORMAT\s*\(/i.test(body)) return true // FORMAT() always yields text
  // SWITCH/IF whose fall-through result is a string literal: …, "Low" )
  if (/^(SWITCH|IF)\s*\(/i.test(body) && /,\s*"[^"]*"\s*\)\s*$/.test(body)) return true
  return false
}

/** Guess a format string from a measure's name + DAX, or null when nothing matches.
 * String literals are stripped first — a filter like ClaimStatus IN {"Paid",…}
 * must not make "Avg_Day_To_Pay" look like currency. */
export function suggestFormat(name: string, dax: string): string | null {
  // Underscores are word chars, so "Avg_Day_To_Pay" defeats \bday\b — normalise them.
  const lowName = name.toLowerCase().replace(/_/g, ' ')
  const n = `${name} ${dax.replace(/"[^"]*"/g, '')}`.toLowerCase().replace(/_/g, ' ')
  if (/%|rate|ratio|pct|percent|margin|share|growth/.test(lowName)) return '0.0%'
  if (/\b(days?|age|duration|los|stay)\b/.test(lowName)) return DEFAULT_FORMAT
  if (/avg|average|mean/.test(lowName) && !/amount|billed|revenue|cost|fee|settlement|collection/.test(n)) return DEFAULT_FORMAT
  if (/amount|billed|paid|revenue|cost|price|fee|settlement|collection|spend|balance/.test(n)) return '\\$#,0.00'
  if (/count|rows|number|qty|quantity|volume/.test(n)) return '#,0'
  return null
}

/** The format a measure should carry. A wrapper like "Billted PY" = CALCULATE([Total_Bill], …)
 * says nothing about itself, so inherit from the single measure it wraps. */
export function resolveFormat(name: string, dax: string, model: SemanticModel, seen: string[] = []): string {
  const own = suggestFormat(name, dax)
  if (own) return own
  if (seen.length > 4) return DEFAULT_FORMAT // pathological cycle guard
  const deps = parseDependencies(dax, model, name).measures.filter((d) => !seen.includes(d.toLowerCase()))
  if (deps.length !== 1) return DEFAULT_FORMAT // ambiguous — don't guess
  const parent = model.tables.flatMap((t) => t.measures).find((m) => m.name.toLowerCase() === deps[0].toLowerCase())
  if (!parent) return DEFAULT_FORMAT
  if (parent.formatString?.trim()) return parent.formatString
  return resolveFormat(parent.name, parent.expression ?? '', model, [...seen, name.toLowerCase()])
}

const isFactLike = (model: SemanticModel, tableName: string): boolean => {
  const t = model.tables.find((x) => x.name.toLowerCase() === tableName.toLowerCase())
  if (!t) return false
  return t.role === 'fact' || (t.rowCount ?? 0) > 500 || /^fact|_fact|bridge/i.test(t.name)
}

/** Analyse every measure in the model. */
export function analyzeModel(model: SemanticModel): Finding[] {
  const findings: Finding[] = []
  const all = model.tables.flatMap((t) => t.measures.map((m) => ({ table: t.name, m })))

  for (const { table, m } of all) {
    if (m.isAutoGenerated) continue // only audit the user's real measures
    const dax = m.expression ?? ''
    const key = `${table}.${m.name}`

    // 1) No format string → renders as a raw number (46856025.71 instead of $46.9M).
    //    Text measures are exempt: a numeric format means nothing to them.
    if ((!m.formatString || !m.formatString.trim()) && !returnsText(dax)) {
      findings.push({
        id: `${key}#format`,
        rule: 'Missing format string',
        severity: 'warning',
        table,
        measure: m.name,
        message: `“${m.name}” has no format string.`,
        why: 'It renders as a raw number in every visual (e.g. 46856025.71 instead of $46.9M).',
        fix: { formatString: resolveFormat(m.name, dax, model) },
      })
    }

    // 2) CALCULATE(..., FILTER(<fact table>, ...)) → scans the whole fact table
    const nakedFilter = dax.match(/FILTER\s*\(\s*'?([A-Za-z_][\w ]*)'?\s*,/i)
    if (/\bCALCULATE\s*\(/i.test(dax) && nakedFilter && isFactLike(model, nakedFilter[1].trim())) {
      const tbl = nakedFilter[1].trim()
      findings.push({
        id: `${key}#nakedfilter`,
        rule: 'FILTER over a whole fact table',
        severity: 'warning',
        table,
        measure: m.name,
        message: `“${m.name}” filters the entire ‘${tbl}’ table inside CALCULATE.`,
        why: 'It materialises every row of the fact table. Filter the column instead — same result, far cheaper at scale.',
        suggestedDax: dax.replace(
          /FILTER\s*\(\s*'?[A-Za-z_][\w ]*'?\s*,\s*([^)]+)\)/i,
          (_m, cond) => `KEEPFILTERS(${String(cond).trim()})`,
        ),
      })
    }

    // 3) Division with "/" → divide-by-zero / blank handling
    if (/[^\/]\/[^\/]/.test(dax) && !/\bDIVIDE\s*\(/i.test(dax)) {
      findings.push({
        id: `${key}#divide`,
        rule: 'Division without DIVIDE()',
        severity: 'warning',
        table,
        measure: m.name,
        message: `“${m.name}” divides with “/” instead of DIVIDE().`,
        why: 'A zero or blank denominator throws an error instead of returning blank. DIVIDE() handles it safely.',
      })
    }

    // 4) Organisation
    if (!m.displayFolder || !m.displayFolder.trim()) {
      findings.push({
        id: `${key}#folder`,
        rule: 'No display folder',
        severity: 'info',
        table,
        measure: m.name,
        message: `“${m.name}” isn’t in a display folder.`,
        why: 'Folders keep a 45-measure model navigable for report authors.',
        fix: { displayFolder: /rate|%|ratio/i.test(m.name) ? 'Ratios' : 'Measures' },
      })
    }
  }

  const order: Record<Severity, number> = { error: 0, warning: 1, info: 2 }
  return findings.sort((a, b) => order[a.severity] - order[b.severity] || a.measure.localeCompare(b.measure))
}

/** Measure → the measures that depend on it (blast radius). */
export function dependents(model: SemanticModel): Record<string, string[]> {
  const map: Record<string, string[]> = {}
  const all = model.tables.flatMap((t) => t.measures)
  for (const m of all) {
    for (const dep of parseDependencies(m.expression, model, m.name).measures) {
      const k = dep.toLowerCase()
      ;(map[k] ??= []).push(m.name)
    }
  }
  return map
}

/** A Markdown data dictionary of the model. */
export function modelDocs(model: SemanticModel): string {
  const lines: string[] = [`# ${model.name} — data dictionary`, '']
  const deps = dependents(model)
  const measureCount = model.tables.reduce((n, t) => n + t.measures.length, 0)
  lines.push(`${model.tables.length} tables · ${measureCount} measures · ${model.relationships.length} relationships`, '')

  lines.push('## Tables', '')
  for (const t of model.tables) {
    if (t.columns.length === 0 && t.measures.length === 0) continue
    lines.push(`### ${t.name}${t.role && t.role !== 'unknown' ? ` _(${t.role})_` : ''}`)
    if (t.rowCount) lines.push(`${t.rowCount.toLocaleString()} rows`, '')
    if (t.columns.length) {
      lines.push('| Column | Type |', '| --- | --- |')
      for (const c of t.columns) lines.push(`| ${c.name} | ${c.dataType} |`)
      lines.push('')
    }
  }

  lines.push('## Measures', '')
  for (const t of model.tables) {
    for (const m of t.measures) {
      if (m.isAutoGenerated) continue
      const used = deps[m.name.toLowerCase()] ?? []
      lines.push(`### ${m.name}`)
      lines.push(`**Table:** ${t.name}${m.displayFolder ? ` · **Folder:** ${m.displayFolder}` : ''}${m.formatString ? ` · **Format:** \`${m.formatString}\`` : ''}`)
      lines.push('', '```dax', m.expression, '```')
      if (used.length) lines.push(`**Used by:** ${used.join(', ')}`)
      lines.push('')
    }
  }

  lines.push('## Relationships', '')
  lines.push('| From | To | Active |', '| --- | --- | --- |')
  const nameOf = (tid: string, cid: string) => {
    const t = model.tables.find((x) => x.id === tid)
    return `${t?.name ?? '?'}[${t?.columns.find((c) => c.id === cid)?.name ?? '?'}]`
  }
  for (const r of model.relationships) {
    lines.push(`| ${nameOf(r.fromTable, r.fromColumn)} | ${nameOf(r.toTable, r.toColumn)} | ${r.isActive ? 'yes' : 'no'} |`)
  }
  return lines.join('\n')
}
