/**
 * APPLICATION — Measure Factory
 * Builds a whole analytical suite for one field in a single pass: each entry is
 * produced by the Intent Engine (so it's the same deterministic, branched DAX),
 * de-duplicated, and ready to verify + deploy together.
 */
import type { SemanticModel, Column } from '@/domain/model'
import type { DatasetData } from '@/application/import/types'
import { suggest } from './intent/suggest'
import { dateColumnCandidates } from './date-table'

export interface SuiteStep {
  name: string
  dax: string
  reason: string
}

export interface SuiteMeasure {
  kindId: string
  label: string
  name: string
  dax: string
  plan: SuiteStep[]
  formatString: string
  preview: { ok: boolean; value?: number; note?: string }
  /** True once the value came from the real engine, not the sample. */
  live?: boolean
  selected: boolean
}

export interface SuiteKind {
  id: string
  label: string
  group: 'Core' | 'Time intelligence' | 'Share & rank'
  needsDate: boolean
  prompt: (field: string) => string
}

/** The catalogue the factory can build for any numeric field. */
export const SUITE_KINDS: SuiteKind[] = [
  { id: 'total', label: 'Total', group: 'Core', needsDate: false, prompt: (f) => `total ${f}` },
  { id: 'average', label: 'Average', group: 'Core', needsDate: false, prompt: (f) => `average ${f}` },
  { id: 'ytd', label: 'Year-to-date', group: 'Time intelligence', needsDate: true, prompt: (f) => `${f} ytd` },
  { id: 'qtd', label: 'Quarter-to-date', group: 'Time intelligence', needsDate: true, prompt: (f) => `${f} qtd` },
  { id: 'mtd', label: 'Month-to-date', group: 'Time intelligence', needsDate: true, prompt: (f) => `${f} mtd` },
  { id: 'prior-year', label: 'Prior year', group: 'Time intelligence', needsDate: true, prompt: (f) => `${f} prior year` },
  { id: 'yoy-pct', label: 'Year-over-year %', group: 'Time intelligence', needsDate: true, prompt: (f) => `${f} year over year growth %` },
  { id: 'mom-pct', label: 'Month-over-month %', group: 'Time intelligence', needsDate: true, prompt: (f) => `${f} month over month growth %` },
  { id: 'moving-avg', label: '3-month moving average', group: 'Time intelligence', needsDate: true, prompt: (f) => `${f} 3 month moving average` },
  { id: 'running', label: 'Running total', group: 'Time intelligence', needsDate: true, prompt: (f) => `${f} running total` },
  { id: 'pct-total', label: '% of total', group: 'Share & rank', needsDate: false, prompt: (f) => `${f} % of total` },
  { id: 'rank', label: 'Rank', group: 'Share & rank', needsDate: false, prompt: (f) => `rank by ${f}` },
]

export const modelHasDate = (model: SemanticModel): boolean =>
  model.tables.some((t) => t.role === 'date' || t.columns.some((c) => c.dataType === 'date' || c.dataType === 'dateTime'))

/** A numeric column is buildable if it's a real additive fact, not a key/date part. */
export function isBuildableColumn(c: Column): boolean {
  if (!/integer|decimal/.test(c.dataType) || c.role === 'key') return false
  if (/(^id$|_id$|id$|key$|code$|year|month|quarter|day|week)/i.test(c.name)) return false
  return true
}

/** Numeric fields the factory can build a suite for (flat, de-duplicated by name). */
export function suiteFields(model: SemanticModel): string[] {
  const out: string[] = []
  for (const t of model.tables) {
    for (const c of t.columns) {
      if (!isBuildableColumn(c)) continue
      if (!out.includes(c.name)) out.push(c.name)
    }
  }
  return out
}

/** Buildable columns grouped by their owning table — drives the Table + Column pickers.
 * Grouping keeps provenance explicit: you always know which table a field lives on,
 * and two tables that share a column name (e.g. both have `Amount`) stay distinct. */
export function suiteColumnsByTable(model: SemanticModel): { table: string; columns: string[] }[] {
  const out: { table: string; columns: string[] }[] = []
  for (const t of model.tables) {
    if (t.isHidden) continue
    const columns = t.columns.filter(isBuildableColumn).map((c) => c.name)
    if (columns.length) out.push({ table: t.name, columns })
  }
  return out
}

/** Every author-created measure in the model, each tagged with its home table.
 * Measures are model-global (referenced as `[Name]`) so this is NOT scoped to one
 * table — it is the pool the Measure picker offers as a base for a time-intel family. */
export function suiteMeasures(model: SemanticModel): { table: string; name: string }[] {
  const out: { table: string; name: string }[] = []
  for (const t of model.tables) {
    for (const m of t.measures) {
      if (m.isAutoGenerated) continue
      out.push({ table: t.name, name: m.name })
    }
  }
  return out
}

/** The table a measure lives on — the natural deploy target for its variants. */
export function measureHomeTable(model: SemanticModel, measureName: string): string | undefined {
  return model.tables.find((t) => t.measures.some((m) => m.name === measureName))?.name
}

/** Build the selected suite for a field. Each entry carries its branched plan.
 * `homeTable`, when given, pins which table the field is read from — the picker
 * passes it so a column name shared by two tables is never resolved to the wrong one. */
export function buildSuite(
  field: string,
  model: SemanticModel,
  datasets: DatasetData[],
  kindIds: string[],
  homeTable?: string,
): SuiteMeasure[] {
  // Pin the aggregated column so every entry is about THIS field — without this
  // the engine can drift to another numeric column on time-intelligence kinds.
  const homeName = resolveFieldHome(model, field, homeTable)
  const valueOverride = homeName ? { table: homeName, column: field } : undefined

  const out: SuiteMeasure[] = []
  const seen = new Set<string>()
  for (const kind of SUITE_KINDS) {
    if (!kindIds.includes(kind.id)) continue
    let picked
    try {
      const { suggestions } = suggest(kind.prompt(field), model, datasets, 4, valueOverride)
      picked = suggestions.find((s) => s.patternId === kind.id) ?? suggestions[0]
    } catch {
      continue
    }
    if (!picked) continue
    // Guard: the entry must actually reference the requested field.
    const touchesField = picked.plan.some((st) => st.dax.includes(`[${field}]`)) || picked.dax.includes(`[${field}]`)
    if (!touchesField) continue

    // Some patterns name the measure generically ("3-Month Moving Avg"). Two suites
    // over different fields would then collide and overwrite each other on deploy,
    // so qualify the final step with the field. Nothing references it downstream.
    let { measureName, plan } = picked
    if (!measureName.toLowerCase().includes(field.toLowerCase())) {
      measureName = `${field} ${measureName}`
      plan = [...plan.slice(0, -1), { ...plan[plan.length - 1], name: measureName }]
    }

    const key = measureName.toLowerCase()
    if (seen.has(key)) continue
    seen.add(key)
    out.push({
      kindId: kind.id,
      label: kind.label,
      name: measureName,
      dax: picked.dax,
      plan,
      formatString: picked.formatString,
      preview: picked.preview,
      selected: true,
    })
  }
  return out
}

/** Every unique measure (base + branches) the selected suite needs, in order. */
export function suitePlan(suite: SuiteMeasure[]): SuiteStep[] {
  const steps: SuiteStep[] = []
  const seen = new Set<string>()
  for (const m of suite.filter((x) => x.selected)) {
    for (const st of m.plan) {
      const k = st.name.toLowerCase()
      if (seen.has(k)) continue
      seen.add(k)
      steps.push(st)
    }
  }
  return steps
}

// ---------------------------------------------------------------------------
// Measure-based suite — build the time-intelligence family for an EXISTING measure
// ---------------------------------------------------------------------------

/** The kinds that are well-defined for any scalar measure. Total/Average are
 * excluded (a measure is already an aggregation); %-of-total and Rank are
 * excluded because they need a grain we cannot infer for an arbitrary measure —
 * we would rather offer fewer kinds than emit DAX that is plausibly wrong. */
export const MEASURE_SUITE_KINDS: SuiteKind[] = SUITE_KINDS.filter((k) =>
  ['ytd', 'qtd', 'mtd', 'prior-year', 'yoy-pct', 'mom-pct', 'moving-avg', 'running'].includes(k.id),
)

interface MeasureWrap {
  /** Short suffix appended to the base measure name, e.g. "YTD". */
  suffix: string
  formatString: string
  /** base is already `[Name]`, dateRef is already `'Table'[Date]`. */
  dax: (base: string, dateRef: string) => string
  reason: (base: string) => string
}

/** The canonical time-intelligence wrappers. These mirror the DAX the Intent
 * Engine emits for a column base, so a measure family reads identically to a
 * column family. Every one is still previewed on the real engine before deploy. */
const MEASURE_WRAP: Record<string, MeasureWrap> = {
  ytd: { suffix: 'YTD', formatString: '#,0', dax: (b, d) => `CALCULATE ( ${b}, DATESYTD ( ${d} ) )`, reason: (b) => `Year-to-date of ${b}.` },
  qtd: { suffix: 'QTD', formatString: '#,0', dax: (b, d) => `CALCULATE ( ${b}, DATESQTD ( ${d} ) )`, reason: (b) => `Quarter-to-date of ${b}.` },
  mtd: { suffix: 'MTD', formatString: '#,0', dax: (b, d) => `CALCULATE ( ${b}, DATESMTD ( ${d} ) )`, reason: (b) => `Month-to-date of ${b}.` },
  'prior-year': { suffix: 'PY', formatString: '#,0', dax: (b, d) => `CALCULATE ( ${b}, SAMEPERIODLASTYEAR ( ${d} ) )`, reason: (b) => `${b} for the same period last year.` },
  'yoy-pct': {
    suffix: 'YoY %', formatString: '0.0%',
    dax: (b, d) => `VAR __cur = ${b}\nVAR __py = CALCULATE ( ${b}, SAMEPERIODLASTYEAR ( ${d} ) )\nRETURN DIVIDE ( __cur - __py, __py )`,
    reason: (b) => `Year-over-year growth of ${b}.`,
  },
  'mom-pct': {
    suffix: 'MoM %', formatString: '0.0%',
    dax: (b, d) => `VAR __cur = ${b}\nVAR __pm = CALCULATE ( ${b}, DATEADD ( ${d}, -1, MONTH ) )\nRETURN DIVIDE ( __cur - __pm, __pm )`,
    reason: (b) => `Month-over-month growth of ${b}.`,
  },
  'moving-avg': {
    suffix: '3M Avg', formatString: '#,0',
    dax: (b, d) => `AVERAGEX ( DATESINPERIOD ( ${d}, MAX ( ${d} ), -3, MONTH ), ${b} )`,
    reason: (b) => `Three-month moving average of ${b}.`,
  },
  running: {
    suffix: 'Running Total', formatString: '#,0',
    dax: (b, d) => `CALCULATE ( ${b}, FILTER ( ALLSELECTED ( ${d} ), ${d} <= MAX ( ${d} ) ) )`,
    reason: (b) => `Running total of ${b} across the visible dates.`,
  },
}

/** The date column time-intelligence should pivot on. Prefer a real date
 * dimension (role `date` or a date-named table) over a raw fact date column,
 * matching how the engine resolves it. */
export function primaryDateColumn(model: SemanticModel): { table: string; column: string } | null {
  const cands = dateColumnCandidates(model)
  if (cands.length === 0) return null
  const norm = (s: string) => s.toLowerCase().replace(/[^a-z]/g, '')
  const DATE_NAMES = ['date', 'calendar', 'dimdate', 'dates', 'time', 'period']
  const dim = cands.find((c) => {
    const t = model.tables.find((x) => x.name === c.table)
    return t?.role === 'date' || DATE_NAMES.some((d) => norm(c.table).includes(d))
  })
  const chosen = dim ?? cands.find((c) => !c.isFact) ?? cands[0]
  return { table: chosen.table, column: chosen.column }
}

/** Which table a field is read from. `preferred` (the table the picker chose)
 * wins when it actually owns the field, so a column name shared by two tables
 * resolves to the one the user selected — never just the first one found. */
export function resolveFieldHome(model: SemanticModel, field: string, preferred?: string): string | undefined {
  const home =
    (preferred && model.tables.find((t) => t.name === preferred && t.columns.some((c) => c.name === field))) ||
    model.tables.find((t) => t.columns.some((c) => c.name === field))
  return home ? home.name : undefined
}

/** Build the selected time-intelligence family for an existing measure. Each
 * entry is a single step (the base measure already exists in the model, so it
 * is referenced, never recreated). Shape matches buildSuite so the dialog's
 * preview + deploy path is identical. */
export function buildSuiteForMeasure(
  measureName: string,
  model: SemanticModel,
  kindIds: string[],
): SuiteMeasure[] {
  const date = primaryDateColumn(model)
  if (!date) return []
  const dateRef = `'${date.table}'[${date.column}]`
  const base = `[${measureName}]`

  const out: SuiteMeasure[] = []
  const seen = new Set<string>()
  for (const kind of MEASURE_SUITE_KINDS) {
    if (!kindIds.includes(kind.id)) continue
    const wrap = MEASURE_WRAP[kind.id]
    if (!wrap) continue
    const name = `${measureName} ${wrap.suffix}`
    const key = name.toLowerCase()
    if (seen.has(key)) continue
    seen.add(key)
    const dax = wrap.dax(base, dateRef)
    out.push({
      kindId: kind.id,
      label: kind.label,
      name,
      dax,
      plan: [{ name, dax, reason: wrap.reason(measureName) }],
      formatString: wrap.formatString,
      // No sample value for a measure base — the real engine fills it in on preview.
      preview: { ok: false, note: 'Verify on the engine' },
      selected: true,
    })
  }
  return out
}
