/**
 * The three-picker Measure Factory: Table scopes Column, Measure is a global
 * alternative base. The column path runs through the tested Intent Engine, but
 * the MEASURE path emits hand-authored time-intelligence DAX — so these tests
 * lock the wrapper shape, the base/date resolution, and the picker groupings.
 */
import { describe, it, expect } from 'vitest'
import {
  suiteColumnsByTable,
  suiteMeasures,
  measureHomeTable,
  primaryDateColumn,
  buildSuiteForMeasure,
  resolveFieldHome,
  MEASURE_SUITE_KINDS,
} from './factory'
import type { SemanticModel, Table, Column, Measure, DataType, ColumnRole, TableRole } from '@/domain/model'

// ---------------------------------------------------------------------------
function col(name: string, dataType: DataType = 'decimal', role: ColumnRole = 'measureCandidate'): Column {
  return { id: name, name, dataType, role }
}
function meas(name: string, expression = 'SUM ( fct[Amount] )'): Measure {
  return { id: name, name, expression }
}
function tbl(name: string, columns: Column[], measures: Measure[] = [], role: TableRole = 'fact'): Table {
  return { id: name, name, role, columns, measures }
}
function makeModel(tables: Table[]): SemanticModel {
  return { tables } as SemanticModel
}

/** A model shaped like the user's: a fact, a date dimension, a _Measures table. */
const MODEL = makeModel([
  tbl('fct_pnl', [col('Amount'), col('Qty', 'integer'), col('client_id', 'integer', 'key')]),
  tbl('fct_billing', [col('Amount'), col('Revenue')]),
  tbl('dim_date', [col('Date', 'date', 'date')], [], 'date'),
  tbl('_Measures', [], [meas('Revenue'), meas('Gross Margin %'), meas('EBITDA')], 'unknown'),
])

// ---------------------------------------------------------------------------
describe('picker data', () => {
  it('groups buildable columns under their own table, keeping shared names distinct', () => {
    const groups = suiteColumnsByTable(MODEL)
    expect(groups).toEqual([
      { table: 'fct_pnl', columns: ['Amount', 'Qty'] }, // client_id is a key → excluded
      { table: 'fct_billing', columns: ['Amount', 'Revenue'] },
    ])
    // The same column name lives under two different tables — that's the point.
    const amountTables = groups.filter((g) => g.columns.includes('Amount')).map((g) => g.table)
    expect(amountTables).toEqual(['fct_pnl', 'fct_billing'])
  })

  it('lists author measures globally, each tagged with its home table', () => {
    expect(suiteMeasures(MODEL)).toEqual([
      { table: '_Measures', name: 'Revenue' },
      { table: '_Measures', name: 'Gross Margin %' },
      { table: '_Measures', name: 'EBITDA' },
    ])
    expect(measureHomeTable(MODEL, 'Revenue')).toBe('_Measures')
    expect(measureHomeTable(MODEL, 'Nope')).toBeUndefined()
  })

  it('excludes hidden tables and auto-generated measures', () => {
    const m = makeModel([
      { ...tbl('Hidden', [col('X')]), isHidden: true },
      tbl('Shown', [col('Y')], [meas('Real'), { ...meas('Auto'), isAutoGenerated: true }]),
    ])
    expect(suiteColumnsByTable(m).map((g) => g.table)).toEqual(['Shown'])
    expect(suiteMeasures(m).map((x) => x.name)).toEqual(['Real'])
  })
})

// ---------------------------------------------------------------------------
describe('primaryDateColumn', () => {
  it('prefers a real date dimension over a raw fact date column', () => {
    const m = makeModel([
      tbl('Sales', [col('OrderDate', 'dateTime', 'date')], [], 'fact'),
      tbl('dim_date', [col('Date', 'date', 'date')], [], 'date'),
    ])
    expect(primaryDateColumn(m)).toEqual({ table: 'dim_date', column: 'Date' })
  })

  it('falls back to a fact date column when no dimension exists', () => {
    const m = makeModel([tbl('Sales', [col('OrderDate', 'dateTime', 'date')], [], 'fact')])
    expect(primaryDateColumn(m)).toEqual({ table: 'Sales', column: 'OrderDate' })
  })

  it('returns null when the model has no date at all', () => {
    expect(primaryDateColumn(makeModel([tbl('T', [col('A')])]))).toBeNull()
  })
})

// ---------------------------------------------------------------------------
describe('buildSuiteForMeasure', () => {
  const all = MEASURE_SUITE_KINDS.map((k) => k.id)

  it('offers only the kinds that are well-defined for a scalar measure', () => {
    // No Total/Average (already aggregated), no %-of-total/Rank (need a grain).
    expect(all.sort()).toEqual(
      ['moving-avg', 'mom-pct', 'prior-year', 'mtd', 'qtd', 'running', 'yoy-pct', 'ytd'].sort(),
    )
  })

  it('wraps the existing measure by reference and pivots on the date dimension', () => {
    const suite = buildSuiteForMeasure('Revenue', MODEL, all)
    const byId = Object.fromEntries(suite.map((s) => [s.kindId, s]))

    expect(byId['ytd'].name).toBe('Revenue YTD')
    expect(byId['ytd'].dax).toBe("CALCULATE ( [Revenue], DATESYTD ( 'dim_date'[Date] ) )")
    expect(byId['prior-year'].dax).toBe("CALCULATE ( [Revenue], SAMEPERIODLASTYEAR ( 'dim_date'[Date] ) )")
    expect(byId['running'].dax).toBe(
      "CALCULATE ( [Revenue], FILTER ( ALLSELECTED ( 'dim_date'[Date] ), 'dim_date'[Date] <= MAX ( 'dim_date'[Date] ) ) )",
    )
    // Every entry references the base measure and none re-defines it.
    for (const s of suite) {
      expect(s.dax).toContain('[Revenue]')
      expect(s.plan).toHaveLength(1)
      expect(s.plan[0].name).toBe(s.name)
    }
  })

  it('marks growth measures as percentages', () => {
    const suite = buildSuiteForMeasure('Revenue', MODEL, all)
    expect(suite.find((s) => s.kindId === 'yoy-pct')!.formatString).toBe('0.0%')
    expect(suite.find((s) => s.kindId === 'ytd')!.formatString).toBe('#,0')
  })

  it('respects the caller\'s kind selection', () => {
    const suite = buildSuiteForMeasure('Revenue', MODEL, ['ytd', 'qtd'])
    expect(suite.map((s) => s.kindId)).toEqual(['ytd', 'qtd'])
  })

  it('builds nothing when there is no date column to pivot on', () => {
    const noDate = makeModel([tbl('_M', [], [meas('Revenue')], 'unknown')])
    expect(buildSuiteForMeasure('Revenue', noDate, all)).toEqual([])
  })

  it('quotes a measure name that contains spaces or symbols', () => {
    const suite = buildSuiteForMeasure('Gross Margin %', MODEL, ['ytd'])
    expect(suite[0].name).toBe('Gross Margin % YTD')
    expect(suite[0].dax).toBe("CALCULATE ( [Gross Margin %], DATESYTD ( 'dim_date'[Date] ) )")
  })
})

// ---------------------------------------------------------------------------
describe('resolveFieldHome (the shared-column ambiguity fix)', () => {
  it('honours the table the picker chose when it owns the field', () => {
    // Both fct_pnl and fct_billing have "Amount". The pin decides which one.
    expect(resolveFieldHome(MODEL, 'Amount', 'fct_billing')).toBe('fct_billing')
    expect(resolveFieldHome(MODEL, 'Amount', 'fct_pnl')).toBe('fct_pnl')
  })

  it('falls back to the first owning table when no pin is given', () => {
    expect(resolveFieldHome(MODEL, 'Amount')).toBe('fct_pnl')
  })

  it('ignores a pin that does not actually own the field', () => {
    // dim_date has no "Amount" — the pin is stale, so fall back rather than trust it.
    expect(resolveFieldHome(MODEL, 'Amount', 'dim_date')).toBe('fct_pnl')
  })

  it('returns undefined for an unknown field', () => {
    expect(resolveFieldHome(MODEL, 'Nope')).toBeUndefined()
  })
})
