/**
 * APPLICATION — NL-to-DAX via NVIDIA NIM
 *
 * Schema-grounded generation: we serialise the live TOM model into a pseudo-SQL
 * DDL string and inject it as the system prompt. The model only ever sees exact
 * names from the schema, so column/table hallucination is near-zero.
 *
 * Flow: modelToSchemaPrompt → callNim → validateDaxNames → NlToDaxResult
 */
import type { SemanticModel } from '@/domain/model'
import { unknownReferences } from './validate'

/**
 * Selectable NIM models. NVIDIA retires models on its own schedule — several
 * IDs that worked recently now return 410 Gone or 404 — so this must never be a
 * single hardcoded constant: when the default dies, the whole feature dies with
 * it and the user has no way out. Anything here can be overridden by typing a
 * model id, so a retirement is a settings change, not a release.
 *
 * Ordering and notes come from an actual benchmark against a live 21-table
 * model (5 prompts x 3 models), not from vendor marketing.
 *
 * Last audited: 2026-09-01. meta/llama-3.1-70b-instruct reached EOL on
 * 2026-08-26 and was replaced by meta/llama-3.3-70b-instruct.
 */
export interface NimModelOption {
  id: string
  label: string
  /** What the benchmark actually showed — shown in the picker. */
  note: string
}

export const NIM_MODELS: NimModelOption[] = [
  {
    id: 'nvidia/llama-3.1-nemotron-70b-instruct',
    label: 'Nemotron 70B',
    note: 'NVIDIA-tuned Llama — good DAX quality, reliably available. ~3-10s.',
  },
  {
    id: 'meta/llama-3.1-405b-instruct',
    label: 'Llama 3.1 405B',
    note: 'Highest quality, slower. Best for complex time intelligence.',
  },
  {
    id: 'meta/llama-3.2-3b-instruct',
    label: 'Llama 3.2 3B',
    note: 'Fastest; weaker on complex time intelligence.',
  },
  {
    id: 'nvidia/llama-3.3-nemotron-super-49b-v1',
    label: 'Nemotron Super 49B',
    note: 'Larger Nemotron variant — try if 70B is unavailable.',
  },
]

/** The default. Chosen for availability + quality after Aug-2026 NIM retirements. */
export const NIM_MODEL = NIM_MODELS[0].id

export interface NlToDaxResult {
  dax: string
  measureName: string
  hallucinated: string[]
  ok: boolean
  note?: string
}

// ---------------------------------------------------------------------------
// Schema serialiser
// ---------------------------------------------------------------------------

function sqlName(name: string): string {
  return /[^A-Za-z0-9_]/.test(name) ? `'${name.replace(/'/g, "''")}'` : name
}

/** Compact pseudo-SQL DDL from the live model — ~3-5 tokens per column. */
export function modelToSchemaPrompt(model: SemanticModel): string {
  const lines: string[] = []

  for (const table of model.tables) {
    if (table.isHidden) continue
    lines.push(`CREATE TABLE ${sqlName(table.name)} (`)
    const visible = table.columns.filter((c) => !c.isHidden)
    const cols = visible
      .slice(0, 30)
      .map((c) => `  ${sqlName(c.name)}  ${normaliseType(c.dataType)}`)
    if (visible.length > 30) cols.push(`  -- … ${visible.length - 30} more columns`)
    lines.push(cols.length ? cols.join(',\n') : '  -- (no visible columns)')
    lines.push(');')
    lines.push('')
  }

  // Existing measures — gives the model context so it can build on them.
  // Cap at 50 to stay inside a reasonable token budget.
  const allMeasures = model.tables.flatMap((t) =>
    t.measures
      .filter((m) => !m.isAutoGenerated)
      .map((m) => ({ tableName: t.name, name: m.name, expression: m.expression })),
  )
  if (allMeasures.length > 0) {
    lines.push('-- Existing measures (reference only — do not redefine them)')
    for (const m of allMeasures.slice(0, 50)) {
      const expr = (m.expression ?? '').split('\n')[0].slice(0, 120)
      lines.push(`MEASURE ${sqlName(m.tableName)}[${m.name}] = ${expr}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

function normaliseType(raw?: string): string {
  if (!raw) return 'VARCHAR'
  const t = raw.toLowerCase()
  if (t.includes('int') || t.includes('whole')) return 'INT'
  if (t.includes('decimal') || t.includes('double') || t.includes('fixed') || t.includes('currency')) return 'DECIMAL'
  if (t.includes('bool')) return 'BOOLEAN'
  if (t.includes('date') && t.includes('time')) return 'DATETIME'
  if (t.includes('date')) return 'DATE'
  return 'VARCHAR'
}

// ---------------------------------------------------------------------------
// NVIDIA NIM call
// ---------------------------------------------------------------------------

const SYSTEM = (schema: string, targetTable: string | undefined) => `\
You are a Power BI DAX expert. Write a single DAX measure expression.

RULES:
1. Use ONLY the exact table and column names from the schema below. Never invent or abbreviate names.
2. Return ONLY the DAX expression — no explanation, no markdown, no "MeasureName = " prefix.
3. If the request cannot be answered from the schema, reply with exactly: CANNOT_GENERATE: <reason>
4. Prefer CALCULATE + FILTER over nested IFs. Use time-intelligence functions (DATESYTD, SAMEPERIODLASTYEAR, etc.) for time calculations.
${targetTable ? `5. The new measure lives in table: ${targetTable}` : ''}

SCHEMA:
${schema}`

export async function generateDaxFromNL(
  userPrompt: string,
  model: SemanticModel,
  apiKey: string,
  targetTable?: string,
  /** Which NIM model to call. Defaults to the benchmarked best. */
  modelId: string = NIM_MODEL,
): Promise<NlToDaxResult> {
  if (!apiKey.trim()) throw new Error('NVIDIA NIM API key is not set.')

  const schema = modelToSchemaPrompt(model)

  // Call goes through the local bridge so the browser never touches an external
  // host directly — avoids CORS and keeps the API key off browser network logs.
  const bridgeBase =
    typeof location !== 'undefined' && location.port === '5177'
      ? location.origin
      : 'http://127.0.0.1:5177'

  const resp = await fetch(`${bridgeBase}/nim`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      apiKey,
      model: modelId,
      messages: [
        { role: 'system', content: SYSTEM(schema, targetTable) },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.1,
      maxTokens: 512,
    }),
    signal: AbortSignal.timeout(90000),
  })

  if (!resp.ok) {
    const err = (await resp.json().catch(() => ({}))) as {
      error?: string | { message?: string }
      message?: string
      detail?: string
    }
    const errMsg =
      (typeof err.error === 'string' ? err.error : err.error?.message) ??
      err.message ??
      err.detail ??
      `NIM error (HTTP ${resp.status})`
    throw new Error(errMsg)
  }

  const data = (await resp.json()) as {
    choices: { message: { content: string } }[]
  }
  const raw = data.choices[0]?.message?.content?.trim() ?? ''

  if (raw.startsWith('CANNOT_GENERATE:')) {
    return {
      dax: '',
      measureName: '',
      hallucinated: [],
      ok: false,
      note: raw.replace(/^CANNOT_GENERATE:\s*/i, '').trim(),
    }
  }

  // DeepSeek R1 wraps reasoning in <think>…</think> — strip it.
  const dax = raw.replace(/<think>[\s\S]*?<\/think>/gi, '').trim()

  const hallucinated = findHallucinatedNames(dax, model)
  const measureName = suggestMeasureName(userPrompt)

  return { dax, measureName, hallucinated, ok: true }
}

// ---------------------------------------------------------------------------
// Name validator
// ---------------------------------------------------------------------------

function findHallucinatedNames(dax: string, model: SemanticModel): string[] {
  // Delegates to the shared validator so tables, columns AND measures are all
  // checked — an invented `ALL(Dates)` or `[Made Up Measure]` is caught, not
  // just a bad column. Same logic the MCP server's validate tool uses.
  return unknownReferences(dax, model)
}

// ---------------------------------------------------------------------------
// Measure name heuristic
// ---------------------------------------------------------------------------

const STOP = new Set(['a', 'an', 'the', 'of', 'for', 'in', 'on', 'at', 'to', 'where', 'is', 'are', 'and', 'or'])

function suggestMeasureName(prompt: string): string {
  const words = prompt
    .replace(/[^a-zA-Z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 1 && !STOP.has(w.toLowerCase()))
    .slice(0, 4)
    .map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase())
  return words.join(' ') || 'New Measure'
}
