/**
 * APPLICATION — NL-to-DAX via NVIDIA NIM (DeepSeek)
 *
 * Schema-grounded generation: we serialise the live TOM model into a pseudo-SQL
 * DDL string and inject it as the system prompt. The model only ever sees exact
 * names from the schema, so column/table hallucination is near-zero.
 *
 * Flow: modelToSchemaPrompt → callNim → validateDaxNames → NlToDaxResult
 */
import type { SemanticModel } from '@/domain/model'
import { parseDependencies } from './dependencies'

export const NIM_MODEL = 'deepseek-ai/deepseek-v4-flash'

export interface NlToDaxResult {
  dax: string
  measureName: string
  hallucinated: string[]
  ok: boolean
  note?: string
}

// ---------------------------------------------------------------------------
// Schema serialiser
// ---------------------------------------------------------------------------

function sqlName(name: string): string {
  return /[^A-Za-z0-9_]/.test(name) ? `'${name.replace(/'/g, "''")}'` : name
}

/** Compact pseudo-SQL DDL from the live model — ~3-5 tokens per column. */
export function modelToSchemaPrompt(model: SemanticModel): string {
  const lines: string[] = []

  for (const table of model.tables) {
    if (table.isHidden) continue
    lines.push(`CREATE TABLE ${sqlName(table.name)} (`)
    const cols = table.columns
      .filter((c) => !c.isHidden)
      .map((c) => `  ${sqlName(c.name)}  ${normaliseType(c.dataType)}`)
    lines.push(cols.length ? cols.join(',\n') : '  -- (no visible columns)')
    lines.push(');')
    lines.push('')
  }

  // Existing measures — gives the model context so it can build on them.
  // Cap at 50 to stay inside a reasonable token budget.
  const allMeasures = model.tables.flatMap((t) =>
    t.measures
      .filter((m) => !m.isAutoGenerated)
      .map((m) => ({ tableName: t.name, name: m.name, expression: m.expression })),
  )
  if (allMeasures.length > 0) {
    lines.push('-- Existing measures (reference only — do not redefine them)')
    for (const m of allMeasures.slice(0, 50)) {
      const expr = (m.expression ?? '').split('\n')[0].slice(0, 120)
      lines.push(`MEASURE ${sqlName(m.tableName)}[${m.name}] = ${expr}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

function normaliseType(raw?: string): string {
  if (!raw) return 'VARCHAR'
  const t = raw.toLowerCase()
  if (t.includes('int') || t.includes('whole')) return 'INT'
  if (t.includes('decimal') || t.includes('double') || t.includes('fixed') || t.includes('currency')) return 'DECIMAL'
  if (t.includes('bool')) return 'BOOLEAN'
  if (t.includes('date') && t.includes('time')) return 'DATETIME'
  if (t.includes('date')) return 'DATE'
  return 'VARCHAR'
}

// ---------------------------------------------------------------------------
// NVIDIA NIM call
// ---------------------------------------------------------------------------

const SYSTEM = (schema: string, targetTable: string | undefined) => `\
You are a Power BI DAX expert. Write a single DAX measure expression.

RULES:
1. Use ONLY the exact table and column names from the schema below. Never invent or abbreviate names.
2. Return ONLY the DAX expression — no explanation, no markdown, no "MeasureName = " prefix.
3. If the request cannot be answered from the schema, reply with exactly: CANNOT_GENERATE: <reason>
4. Prefer CALCULATE + FILTER over nested IFs. Use time-intelligence functions (DATESYTD, SAMEPERIODLASTYEAR, etc.) for time calculations.
${targetTable ? `5. The new measure lives in table: ${targetTable}` : ''}

SCHEMA:
${schema}`

export async function generateDaxFromNL(
  userPrompt: string,
  model: SemanticModel,
  apiKey: string,
  targetTable?: string,
): Promise<NlToDaxResult> {
  if (!apiKey.trim()) throw new Error('NVIDIA NIM API key is not set.')

  const schema = modelToSchemaPrompt(model)

  // Call goes through the local bridge so the browser never touches an external
  // host directly — avoids CORS and keeps the API key off browser network logs.
  const bridgeBase =
    typeof location !== 'undefined' && location.port === '5177'
      ? location.origin
      : 'http://127.0.0.1:5177'

  const resp = await fetch(`${bridgeBase}/nim`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      apiKey,
      model: NIM_MODEL,
      messages: [
        { role: 'system', content: SYSTEM(schema, targetTable) },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.1,
      maxTokens: 512,
    }),
    signal: AbortSignal.timeout(30000),
  })

  if (!resp.ok) {
    const err = (await resp.json().catch(() => ({}))) as {
      error?: string | { message?: string }
      message?: string
      detail?: string
    }
    const errMsg =
      (typeof err.error === 'string' ? err.error : err.error?.message) ??
      err.message ??
      err.detail ??
      `NIM error (HTTP ${resp.status})`
    throw new Error(errMsg)
  }

  const data = (await resp.json()) as {
    choices: { message: { content: string } }[]
  }
  const raw = data.choices[0]?.message?.content?.trim() ?? ''

  if (raw.startsWith('CANNOT_GENERATE:')) {
    return {
      dax: '',
      measureName: '',
      hallucinated: [],
      ok: false,
      note: raw.replace(/^CANNOT_GENERATE:\s*/i, '').trim(),
    }
  }

  // DeepSeek R1 wraps reasoning in <think>…</think> — strip it.
  const dax = raw.replace(/<think>[\s\S]*?<\/think>/gi, '').trim()

  const hallucinated = findHallucinatedNames(dax, model)
  const measureName = suggestMeasureName(userPrompt)

  return { dax, measureName, hallucinated, ok: true }
}

// ---------------------------------------------------------------------------
// Name validator
// ---------------------------------------------------------------------------

function findHallucinatedNames(dax: string, model: SemanticModel): string[] {
  const deps = parseDependencies(dax, model)
  const allColKeys = new Set(
    model.tables.flatMap((t) =>
      t.columns.map((c) => `${t.name.toLowerCase()}[${c.name.toLowerCase()}]`),
    ),
  )
  return deps.columns
    .filter((col) => !allColKeys.has(`${col.table.toLowerCase()}[${col.column.toLowerCase()}]`))
    .map((col) => `${col.table}[${col.column}]`)
}

// ---------------------------------------------------------------------------
// Measure name heuristic
// ---------------------------------------------------------------------------

const STOP = new Set(['a', 'an', 'the', 'of', 'for', 'in', 'on', 'at', 'to', 'where', 'is', 'are', 'and', 'or'])

function suggestMeasureName(prompt: string): string {
  const words = prompt
    .replace(/[^a-zA-Z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 1 && !STOP.has(w.toLowerCase()))
    .slice(0, 4)
    .map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase())
  return words.join(' ') || 'New Measure'
}
