/**
 * APPLICATION — model object usage & impact analysis (pure)
 *
 * Answers three questions for the Cleanup surface:
 *   1. What does each object depend on, and what depends on it?
 *   2. Is it safe to delete — and can we actually PROVE that?
 *   3. If we delete it, what breaks (transitively)?
 *
 * The honesty rule: the Analysis Services engine exposes the MODEL only. It
 * knows nothing about report pages or visuals, so a measure with zero model
 * dependents may still be bound to dozens of visuals. We therefore never
 * claim "unused" unless a report layer was actually scanned.
 */
import type { SemanticModel } from '@/domain/model'
import { parseDependencies } from './dependencies'

export type ObjectKind = 'measure' | 'column' | 'table'

/**
 * referenced    — something in the model provably uses it.
 * no-model-refs — nothing in the model uses it, but the report layer was not
 *                 scanned, so visual usage is UNKNOWN. Not safe to bulk-delete.
 * unused        — no model refs AND the report layer was scanned and does not
 *                 bind it. Provably safe.
 */
export type UsageState = 'referenced' | 'no-model-refs' | 'unused'

/** Where in the report an object is bound — one row per page + visual pair. */
export interface VisualPlacement {
  page: string
  /** Power BI's own visual type id, e.g. "clusteredBarChart", "card". */
  visualType: string
}

/** Visual/report bindings, when a PBIP or PBIX was available to parse. */
export interface ReportUsage {
  /** False means "we never looked" — the difference between unknown and zero. */
  scanned: boolean
  /** lowercase measure name -> number of visual bindings */
  measures: Record<string, number>
  /** columnUsageKey() -> number of visual bindings */
  columns: Record<string, number>
  /** lowercase measure name -> the pages/visuals it appears on */
  measurePlacements?: Record<string, VisualPlacement[]>
  /** columnUsageKey() -> the pages/visuals it appears on */
  columnPlacements?: Record<string, VisualPlacement[]>
}

export const NO_REPORT: ReportUsage = { scanned: false, measures: {}, columns: {} }

/** Collision-proof composite key (JSON quoting keeps 'A B'+'C' != 'A'+'B C'). */
export function objectKey(kind: ObjectKind, table: string, name: string): string {
  return JSON.stringify([kind, table.toLowerCase(), name.toLowerCase()])
}
export function columnUsageKey(table: string, column: string): string {
  return JSON.stringify([table.toLowerCase(), column.toLowerCase()])
}

export interface UsageNode {
  key: string
  kind: ObjectKind
  table: string
  name: string
  /** Display label: "Table[Column]", "[Measure]", "Table" */
  label: string
  state: UsageState
  /** Object keys this node references. */
  dependsOn: string[]
  /** Object keys that reference this node — deleting it breaks these. */
  dependents: string[]
  /** Human-readable reasons it counts as used (incl. non-object usage). */
  reasons: string[]
  /** Visual bindings found in the report layer (0 when not scanned). */
  reportRefs: number
  /** Which pages and visual types bind it. Empty unless a report was scanned. */
  placements: VisualPlacement[]
  /** The measure's DAX, so the detail panel need not re-query the model. */
  dax?: string
  /** True when it sits on a relationship — deleting it breaks the model. */
  inRelationship: boolean
  /**
   * DAX references only, excluding containment. A table "contains" its columns
   * and measures, which would otherwise make every non-empty table look used.
   */
  directRefs: number
}

export interface UsageGraph {
  nodes: UsageNode[]
  byKey: Record<string, UsageNode>
  /** Whether a report layer was scanned; gates every "unused" claim. */
  scanned: boolean
  /** Measure cycles, if any. The engine normally forbids these. */
  cycles: string[][]
}

export function buildUsageGraph(model: SemanticModel, report: ReportUsage = NO_REPORT): UsageGraph {
  const byKey: Record<string, UsageNode> = {}
  const nodes: UsageNode[] = []

  const add = (kind: ObjectKind, table: string, name: string, label: string) => {
    const key = objectKey(kind, table, name)
    if (byKey[key]) return byKey[key]
    const node: UsageNode = {
      key, kind, table, name, label,
      state: 'no-model-refs',
      dependsOn: [], dependents: [], reasons: [],
      reportRefs: 0, placements: [], inRelationship: false, directRefs: 0,
    }
    byKey[key] = node
    nodes.push(node)
    return node
  }

  // ---- 1. every object becomes a node.
  // Auto-generated measures are Workbench-side artifacts (auto-model / KPI
  // engine), not objects in the user's Power BI model — offering to delete
  // them would be meaningless. Model Doctor skips them for the same reason.
  const scoped: SemanticModel = {
    ...model,
    tables: model.tables.map((t) => ({ ...t, measures: t.measures.filter((mm) => !mm.isAutoGenerated) })),
  }

  for (const t of scoped.tables) {
    add('table', t.name, t.name, t.name)
    for (const c of t.columns) add('column', t.name, c.name, `${t.name}[${c.name}]`)
    for (const mm of t.measures) {
      const n = add('measure', t.name, mm.name, `[${mm.name}]`)
      n.dax = mm.expression ?? ''
    }
  }

  const link = (fromKey: string, toKey: string) => {
    const from = byKey[fromKey]
    const to = byKey[toKey]
    if (!from || !to || from === to) return
    if (!from.dependsOn.includes(toKey)) from.dependsOn.push(toKey)
    if (!to.dependents.includes(fromKey)) to.dependents.push(fromKey)
  }

  // Measure names are unique model-wide in DAX, so name -> home table resolves.
  const measureHome = new Map<string, string>()
  for (const t of scoped.tables) for (const mm of t.measures) measureHome.set(mm.name.toLowerCase(), t.name)
  // Column name -> every table carrying it (for unqualified row-context refs).
  const columnHomes = new Map<string, string[]>()
  for (const t of scoped.tables)
    for (const c of t.columns) {
      const k = c.name.toLowerCase()
      columnHomes.set(k, [...(columnHomes.get(k) ?? []), t.name])
    }

  // ---- 2. DAX edges from every measure expression
  for (const t of scoped.tables) {
    for (const mm of t.measures) {
      const selfKey = objectKey('measure', t.name, mm.name)
      const deps = parseDependencies(mm.expression ?? '', scoped, mm.name)

      for (const dm of deps.measures) {
        const home = measureHome.get(dm.toLowerCase())
        if (!home) continue
        const k = objectKey('measure', home, dm)
        link(selfKey, k)
        if (byKey[k]) byKey[k].directRefs++
      }
      for (const dc of deps.columns) {
        const k = objectKey('column', dc.table, dc.column)
        link(selfKey, k)
        if (byKey[k]) byKey[k].directRefs++
      }
      for (const dt of deps.tables) {
        const k = objectKey('table', dt, dt)
        link(selfKey, k)
        if (byKey[k]) byKey[k].directRefs++
      }
      // Unqualified [Col] — home table unknowable, so bind to EVERY candidate.
      // Over-reporting here blocks a delete; under-reporting would lose data.
      for (const u of deps.unqualified)
        for (const home of columnHomes.get(u.toLowerCase()) ?? []) {
          const k = objectKey('column', home, u)
          link(selfKey, k)
          if (byKey[k]) byKey[k].directRefs++
        }
    }
  }

  // ---- 3. containment: deleting a table takes its columns and measures with it
  for (const t of scoped.tables) {
    const tKey = objectKey('table', t.name, t.name)
    for (const c of t.columns) link(objectKey('column', t.name, c.name), tKey)
    for (const mm of t.measures) link(objectKey('measure', t.name, mm.name), tKey)
  }

  // ---- 4. relationships pin their columns (invisible to DAX parsing)
  const tableById = new Map(scoped.tables.map((t) => [t.id, t]))
  const colById = new Map(scoped.tables.flatMap((t) => t.columns.map((c) => [c.id, { t, c }] as const)))
  for (const r of scoped.relationships) {
    for (const side of [r.fromColumn, r.toColumn]) {
      const hit = colById.get(side)
      if (!hit) continue
      const n = byKey[objectKey('column', hit.t.name, hit.c.name)]
      if (n) {
        n.inRelationship = true
        n.reasons.push('Used by a relationship')
      }
    }
    for (const side of [r.fromTable, r.toTable]) {
      const t = tableById.get(side)
      if (!t) continue
      const n = byKey[objectKey('table', t.name, t.name)]
      if (n) {
        n.inRelationship = true
        if (!n.reasons.includes('Joined by a relationship')) n.reasons.push('Joined by a relationship')
      }
    }
  }

  // ---- 5. report-layer bindings
  if (report.scanned) {
    for (const n of nodes) {
      const key = n.kind === 'measure' ? n.name.toLowerCase() : columnUsageKey(n.table, n.name)
      const hits =
        n.kind === 'measure'
          ? (report.measures[key] ?? 0)
          : n.kind === 'column'
            ? (report.columns[key] ?? 0)
            : 0
      n.reportRefs = hits
      n.placements =
        n.kind === 'measure'
          ? (report.measurePlacements?.[key] ?? [])
          : n.kind === 'column'
            ? (report.columnPlacements?.[key] ?? [])
            : []
      if (hits > 0) n.reasons.push(`Bound to ${hits} visual${hits === 1 ? '' : 's'}`)
    }
  }

  // ---- 6. resolve state — measures and columns first, tables last (a table's
  //         verdict depends on whether anything inside it survived)
  const resolve = (n: UsageNode, usedInModel: boolean) => {
    if (usedInModel || n.reportRefs > 0) n.state = 'referenced'
    else if (report.scanned) n.state = 'unused'
    else n.state = 'no-model-refs'
  }

  for (const n of nodes) {
    if (n.kind === 'table') continue
    const refs = n.dependents.filter((k) => byKey[k]?.kind === 'measure').length
    if (refs > 0) n.reasons.unshift(`${refs} measure${refs === 1 ? '' : 's'} reference it`)
    resolve(n, n.dependents.length > 0 || n.inRelationship)
  }

  for (const n of nodes) {
    if (n.kind !== 'table') continue
    const inside = nodes.filter((x) => x.kind !== 'table' && x.table === n.table)
    const liveInside = inside.filter((x) => x.state === 'referenced').length
    if (n.directRefs > 0) n.reasons.unshift(`Referenced by ${n.directRefs} DAX expression${n.directRefs === 1 ? '' : 's'}`)
    if (liveInside > 0) n.reasons.push(`Holds ${liveInside} object${liveInside === 1 ? '' : 's'} still in use`)
    resolve(n, n.directRefs > 0 || n.inRelationship || liveInside > 0)
  }

  return { nodes, byKey, scanned: report.scanned, cycles: findCycles(byKey) }
}

/**
 * Everything that breaks if `keys` are deleted — transitive dependents,
 * excluding the deleted set itself.
 */
export function cascadeImpact(graph: UsageGraph, keys: string[]): string[] {
  const doomed = new Set(keys)
  const out = new Set<string>()
  const queue = [...keys]
  while (queue.length) {
    const cur = queue.shift()!
    for (const d of graph.byKey[cur]?.dependents ?? []) {
      if (doomed.has(d) || out.has(d)) continue
      out.add(d)
      queue.push(d)
    }
  }
  return [...out]
}

/** Deletion order: dependents first, so nothing is orphaned mid-deploy. */
export function deletionOrder(graph: UsageGraph, keys: string[]): string[] {
  const set = new Set(keys)
  const seen = new Set<string>()
  const out: string[] = []
  const visit = (k: string) => {
    if (seen.has(k) || !set.has(k)) return
    seen.add(k)
    for (const d of graph.byKey[k]?.dependents ?? []) visit(d)
    out.push(k)
  }
  for (const k of keys) visit(k)
  return out
}

/** Measure->measure cycles. Rare (the engine rejects them) but cheap to check. */
function findCycles(byKey: Record<string, UsageNode>): string[][] {
  const cycles: string[][] = []
  const state = new Map<string, 0 | 1 | 2>()
  const stack: string[] = []
  const walk = (k: string) => {
    const st = state.get(k) ?? 0
    if (st === 1) {
      const at = stack.indexOf(k)
      if (at >= 0) cycles.push(stack.slice(at).concat(k))
      return
    }
    if (st === 2) return
    state.set(k, 1)
    stack.push(k)
    for (const d of byKey[k]?.dependsOn ?? []) if (byKey[d]?.kind === 'measure') walk(d)
    stack.pop()
    state.set(k, 2)
  }
  for (const k of Object.keys(byKey)) if (byKey[k].kind === 'measure') walk(k)
  return cycles
}
