import { create } from 'zustand'
import type { Measure, Relationship, SemanticModel, Table } from '@/domain/model'
import { emptyModel } from '@/domain/model'
import type { Rect, Report, Visual } from '@/domain/report'
import { emptyReport } from '@/domain/report'
import type { DatasetData } from '@/application/import/types'
import { buildModel } from '@/application/model/auto-model'
import { generateDashboard } from '@/application/insights/dashboard-generator'
import type { TemplateDef } from '@/application/templates/catalog'
import { makeTemplateFile } from '@/application/templates/generate'
import { applyAccent, resetAccent } from '@/design-system/runtime-theme'
import { services } from './services'

export interface PendingTable {
  id: string
  name: string
  rowCount: number
  columnCount: number
  table: Table
  data: DatasetData
}

export interface PendingImport {
  tables: PendingTable[]
  relationships: number
  fileNames: string[]
  currentTables: number
  currentMeasures: number
  isSampleData: boolean
  templateName: string | null
}

/** Run the auto-model engine over the current datasets + tables. */
function analyze(
  datasets: DatasetData[],
  tables: Table[],
): { tables: Table[]; relationships: Relationship[] } {
  const inputs = datasets
    .map((data) => {
      const table = tables.find((t) => t.id === data.id)
      return table ? { data, table } : null
    })
    .filter((x): x is { data: DatasetData; table: Table } => x !== null)
  if (inputs.length === 0) return { tables, relationships: [] }
  const res = buildModel(inputs)
  return { tables: res.tables, relationships: res.relationships }
}

/** Generate measures + an auto-dashboard from a model; attach measures to tables. */
function buildArtifacts(model: SemanticModel): { model: SemanticModel; report: Report } {
  const { page, measures } = generateDashboard(model)
  const tables = model.tables.map((t) => {
    const measuresForTable: Measure[] = measures
      .filter((m) => m.tableId === t.id)
      .map((m) => ({
        id: m.id,
        name: m.name,
        expression: m.dax.includes(' = ') ? m.dax.split(' = ').slice(1).join(' = ') : m.dax,
        formatString: m.formatString,
        displayFolder: m.displayFolder,
        description: `Auto-generated ${m.kind} measure`,
        confidence: m.confidence,
        isAutoGenerated: true,
      }))
    return { ...t, measures: measuresForTable }
  })
  const report: Report = {
    id: 'report',
    name: 'Report',
    pages: [page],
    activePageId: page.id,
    themeId: 'studio',
  }
  return { model: { ...model, tables }, report }
}

export type View = 'home' | 'studio'
export type Theme = 'light' | 'dark'
export type StudioMode = 'design' | 'data' | 'model' | 'dax'

interface PanelState {
  left: boolean
  right: boolean
  bottom: boolean
}

interface AppState {
  view: View
  theme: Theme
  mode: StudioMode
  panels: PanelState
  commandPaletteOpen: boolean
  projectName: string | null
  activeTemplateId: string | null

  // ---- document state ----
  model: SemanticModel
  report: Report
  datasets: DatasetData[]
  activeDatasetId: string | null

  // ---- designer ----
  selectedVisualId: string | null
  past: Report[]
  future: Report[]

  // ---- DAX ----
  selectedMeasureId: string | null

  // ---- analyst ----
  analystOpen: boolean
  analystThinking: boolean
  analystMessages: AnalystMessage[]

  // ---- export ----
  exportOpen: boolean

  // ---- plugins ----
  pluginsOpen: boolean

  // ---- import ----
  importing: boolean
  importError: string | null
  pendingImport: PendingImport | null
  _pickFiles: (() => void) | null

  // ---- actions ----
  goHome: () => void
  openStudio: (projectName: string) => void
  applyTemplate: (def: TemplateDef) => Promise<void>
  setMode: (mode: StudioMode) => void
  toggleTheme: () => void
  setTheme: (t: Theme) => void
  togglePanel: (panel: keyof PanelState) => void
  setCommandPalette: (open: boolean) => void

  registerFilePicker: (fn: () => void) => void
  requestImport: () => void
  importFiles: (files: File[]) => Promise<void>
  stageImport: (files: File[]) => Promise<void>
  commitImport: (selectedIds: string[], mode: 'replace' | 'merge') => void
  cancelImport: () => void
  setActiveDataset: (id: string) => void
  dismissImportError: () => void
  runAutoModel: () => void
  generateDashboard: () => void

  // designer actions
  selectVisual: (id: string | null) => void
  beginChange: () => void
  setVisualRect: (id: string, rect: Rect) => void
  updateVisual: (id: string, patch: Partial<Visual>) => void
  addVisual: (visual: Visual) => void
  duplicateVisual: (id: string) => void
  deleteVisual: (id: string) => void
  nudgeVisual: (id: string, dx: number, dy: number) => void
  undo: () => void
  redo: () => void

  // DAX actions
  selectMeasure: (id: string | null) => void
  addMeasure: () => void
  updateMeasure: (id: string, patch: Partial<Measure>) => void
  deleteMeasure: (id: string) => void

  // analyst actions
  toggleAnalyst: (open?: boolean) => void
  askAnalyst: (question: string) => Promise<void>

  // export
  toggleExport: (open?: boolean) => void

  // plugins
  togglePlugins: (open?: boolean) => void
}

export interface AnalystMessage {
  id: string
  role: 'user' | 'assistant'
  text: string
  chips?: string[]
}

let msgSeq = 0

const cloneReport = (r: Report): Report => structuredClone(r)

/** Replace the active page's visuals immutably. */
function withVisuals(report: Report, fn: (v: Visual[]) => Visual[]): Report {
  return {
    ...report,
    pages: report.pages.map((p) =>
      p.id === (report.activePageId ?? report.pages[0]?.id)
        ? { ...p, visuals: fn(p.visuals) }
        : p,
    ),
  }
}

const applyTheme = (t: Theme) => {
  document.documentElement.setAttribute('data-theme', t)
  try {
    localStorage.setItem('pbs.theme', t)
  } catch {
    /* storage may be unavailable — non-fatal */
  }
}

const initialTheme: Theme =
  (document.documentElement.getAttribute('data-theme') as Theme) || 'light'

/** Ensure a dataset id is unique against existing + newly-added datasets. */
function uniqueId(base: string, taken: Set<string>): string {
  if (!taken.has(base)) return base
  let n = 2
  while (taken.has(`${base}_${n}`)) n++
  return `${base}_${n}`
}

export const useApp = create<AppState>((set, get) => ({
  view: 'home',
  theme: initialTheme,
  mode: 'design',
  panels: { left: true, right: true, bottom: false },
  commandPaletteOpen: false,
  projectName: null,
  activeTemplateId: null,

  model: emptyModel('model', 'Model'),
  report: emptyReport('report', 'Report'),
  datasets: [],
  activeDatasetId: null,

  selectedVisualId: null,
  past: [],
  future: [],

  selectedMeasureId: null,

  analystOpen: false,
  analystThinking: false,
  analystMessages: [],

  exportOpen: false,
  pluginsOpen: false,

  importing: false,
  importError: null,
  pendingImport: null,
  _pickFiles: null,

  goHome: () => set({ view: 'home' }),

  openStudio: (projectName) => set({ view: 'studio', projectName, mode: 'design' }),

  applyTemplate: async (def) => {
    applyAccent(def.accent)
    get().setTheme(def.mode)
    // Fresh document so the template's data + dashboard replace any prior project.
    set({
      activeTemplateId: def.id,
      projectName: def.name,
      datasets: [],
      model: emptyModel('model', 'Model'),
      report: emptyReport('report', 'Report'),
      selectedVisualId: null,
      selectedMeasureId: null,
      activeDatasetId: null,
      past: [],
      future: [],
    })
    await get().importFiles([makeTemplateFile(def)])
  },

  setMode: (mode) => set({ mode }),

  toggleTheme: () => {
    const next: Theme = get().theme === 'light' ? 'dark' : 'light'
    applyTheme(next)
    set({ theme: next })
  },

  setTheme: (t) => {
    applyTheme(t)
    set({ theme: t })
  },

  togglePanel: (panel) =>
    set((s) => ({ panels: { ...s.panels, [panel]: !s.panels[panel] } })),

  setCommandPalette: (open) => set({ commandPaletteOpen: open }),

  registerFilePicker: (fn) => set({ _pickFiles: fn }),

  requestImport: () => {
    const pick = get()._pickFiles
    if (pick) pick()
  },

  importFiles: async (files) => {
    if (files.length === 0) return
    set({ importing: true, importError: null })

    const svc = services.import()
    const taken = new Set(get().datasets.map((d) => d.id))
    const addedData: DatasetData[] = []
    const addedTables: SemanticModel['tables'] = []
    let firstId: string | null = null
    let error: string | null = null

    for (const file of files) {
      const res = await svc.importFile(file)
      if (res.ok) {
        for (const imported of res.value) {
          const id = uniqueId(imported.data.id, taken)
          taken.add(id)
          const data = { ...imported.data, id }
          // Re-base column ids onto the final (deduped) table id.
          const columns = imported.table.columns.map((c) => ({
            ...c,
            id: `${id}::${c.id.split('::').pop() ?? c.name}`,
          }))
          const table = { ...imported.table, id, columns }
          addedData.push(data)
          addedTables.push(table)
          firstId ??= id
        }
      } else {
        error = res.error
      }
    }

    set((s) => {
      const datasets = [...s.datasets, ...addedData]
      const mergedTables = [...s.model.tables, ...addedTables]
      const analyzed = analyze(datasets, mergedTables)
      const modeled: SemanticModel = {
        ...s.model,
        tables: analyzed.tables,
        relationships: analyzed.relationships,
      }
      const artifacts = buildArtifacts(modeled)
      const hasDashboard = (artifacts.report.pages[0]?.visuals.length ?? 0) > 0
      const imported = addedData.length > 0
      return {
        datasets,
        model: artifacts.model,
        report: artifacts.report,
        activeDatasetId: firstId ?? s.activeDatasetId,
        importing: false,
        importError: error,
        view: imported ? 'studio' : s.view,
        mode: imported ? (hasDashboard ? 'design' : 'data') : s.mode,
        projectName: s.projectName ?? addedData[0]?.name ?? null,
        selectedVisualId: null,
        past: [],
        future: [],
      }
    })
  },

  // Parse files and open the confirmation dialog (no commit yet).
  stageImport: async (files) => {
    if (files.length === 0) return
    set({ importing: true, importError: null })

    const svc = services.import()
    const taken = new Set<string>()
    const pendingTables: PendingTable[] = []
    let error: string | null = null

    for (const file of files) {
      const res = await svc.importFile(file)
      if (res.ok) {
        for (const imported of res.value) {
          const id = uniqueId(imported.data.id, taken)
          taken.add(id)
          const data = { ...imported.data, id }
          const columns = imported.table.columns.map((c) => ({
            ...c,
            id: `${id}::${c.id.split('::').pop() ?? c.name}`,
          }))
          const table = { ...imported.table, id, columns }
          pendingTables.push({
            id,
            name: table.name,
            rowCount: data.rowCount,
            columnCount: data.columns.length,
            table,
            data,
          })
        }
      } else {
        error = res.error
      }
    }

    if (pendingTables.length === 0) {
      set({ importing: false, importError: error ?? 'Nothing to import.' })
      return
    }

    const preview = buildModel(pendingTables.map((p) => ({ table: p.table, data: p.data })))
    const s = get()
    set({
      importing: false,
      importError: error,
      pendingImport: {
        tables: pendingTables,
        relationships: preview.relationships.filter((r) => r.isActive).length,
        fileNames: [...new Set(files.map((f) => f.name))],
        currentTables: s.datasets.length,
        currentMeasures: s.model.tables.reduce((n, t) => n + t.measures.length, 0),
        isSampleData: s.activeTemplateId !== null,
        templateName: s.activeTemplateId !== null ? s.projectName : null,
      },
    })
  },

  commitImport: (selectedIds, mode) =>
    set((s) => {
      const pending = s.pendingImport
      if (!pending) return {}
      const selected = pending.tables.filter((t) => selectedIds.includes(t.id))
      if (selected.length === 0) return { pendingImport: null }

      let datasets: DatasetData[]
      let tables: Table[]

      if (mode === 'merge') {
        const taken = new Set(s.datasets.map((d) => d.id))
        const addData: DatasetData[] = []
        const addTables: Table[] = []
        for (const p of selected) {
          const id = uniqueId(p.id, taken)
          taken.add(id)
          addData.push({ ...p.data, id })
          addTables.push({
            ...p.table,
            id,
            columns: p.table.columns.map((c) => ({ ...c, id: `${id}::${c.id.split('::').pop() ?? c.name}` })),
          })
        }
        datasets = [...s.datasets, ...addData]
        tables = [...s.model.tables, ...addTables]
      } else {
        datasets = selected.map((p) => p.data)
        tables = selected.map((p) => p.table)
      }

      const analyzed = analyze(datasets, tables)
      const baseModel: SemanticModel =
        mode === 'merge'
          ? { ...s.model, tables: analyzed.tables, relationships: analyzed.relationships }
          : { ...emptyModel('model', 'Model'), tables: analyzed.tables, relationships: analyzed.relationships }
      const artifacts = buildArtifacts(baseModel)
      const hasDashboard = (artifacts.report.pages[0]?.visuals.length ?? 0) > 0

      if (mode === 'replace') resetAccent()

      return {
        datasets,
        model: artifacts.model,
        report: artifacts.report,
        activeDatasetId: datasets[0]?.id ?? null,
        activeTemplateId: mode === 'replace' ? null : s.activeTemplateId,
        projectName:
          mode === 'replace'
            ? pending.fileNames[0]?.replace(/\.[^.]+$/, '') ?? selected[0]?.name ?? 'Imported'
            : s.projectName,
        view: 'studio',
        mode: hasDashboard ? 'design' : 'data',
        pendingImport: null,
        selectedVisualId: null,
        selectedMeasureId: null,
        past: [],
        future: [],
      }
    }),

  cancelImport: () => set({ pendingImport: null }),

  setActiveDataset: (id) => set({ activeDatasetId: id, mode: 'data' }),

  dismissImportError: () => set({ importError: null }),

  runAutoModel: () =>
    set((s) => {
      const analyzed = analyze(s.datasets, s.model.tables)
      const modeled: SemanticModel = {
        ...s.model,
        tables: analyzed.tables,
        relationships: analyzed.relationships,
      }
      const artifacts = buildArtifacts(modeled)
      return { model: artifacts.model, report: artifacts.report }
    }),

  generateDashboard: () =>
    set((s) => {
      const artifacts = buildArtifacts(s.model)
      return {
        model: artifacts.model,
        report: artifacts.report,
        mode: 'design',
        selectedVisualId: null,
        past: [],
        future: [],
      }
    }),

  // ---- designer ----
  selectVisual: (id) => set({ selectedVisualId: id }),

  beginChange: () =>
    set((s) => ({ past: [...s.past, cloneReport(s.report)].slice(-50), future: [] })),

  setVisualRect: (id, rect) =>
    set((s) => ({
      report: withVisuals(s.report, (vs) => vs.map((v) => (v.id === id ? { ...v, rect } : v))),
    })),

  updateVisual: (id, patch) =>
    set((s) => ({
      report: withVisuals(s.report, (vs) => vs.map((v) => (v.id === id ? { ...v, ...patch } : v))),
    })),

  addVisual: (visual) =>
    set((s) => ({
      past: [...s.past, cloneReport(s.report)].slice(-50),
      future: [],
      report: withVisuals(s.report, (vs) => [...vs, visual]),
      selectedVisualId: visual.id,
    })),

  duplicateVisual: (id) =>
    set((s) => {
      const page = s.report.pages.find((p) => p.id === s.report.activePageId) ?? s.report.pages[0]
      const src = page?.visuals.find((v) => v.id === id)
      if (!src) return {}
      const copy: Visual = {
        ...structuredClone(src),
        id: `v_${Date.now().toString(36)}`,
        rect: { ...src.rect, x: src.rect.x + 24, y: src.rect.y + 24 },
      }
      return {
        past: [...s.past, cloneReport(s.report)].slice(-50),
        future: [],
        report: withVisuals(s.report, (vs) => [...vs, copy]),
        selectedVisualId: copy.id,
      }
    }),

  deleteVisual: (id) =>
    set((s) => ({
      past: [...s.past, cloneReport(s.report)].slice(-50),
      future: [],
      report: withVisuals(s.report, (vs) => vs.filter((v) => v.id !== id)),
      selectedVisualId: s.selectedVisualId === id ? null : s.selectedVisualId,
    })),

  nudgeVisual: (id, dx, dy) =>
    set((s) => ({
      past: [...s.past, cloneReport(s.report)].slice(-50),
      future: [],
      report: withVisuals(s.report, (vs) =>
        vs.map((v) =>
          v.id === id
            ? { ...v, rect: { ...v.rect, x: Math.max(0, v.rect.x + dx), y: Math.max(0, v.rect.y + dy) } }
            : v,
        ),
      ),
    })),

  undo: () =>
    set((s) => {
      if (s.past.length === 0) return {}
      const previous = s.past[s.past.length - 1]
      return {
        past: s.past.slice(0, -1),
        future: [cloneReport(s.report), ...s.future].slice(0, 50),
        report: previous,
      }
    }),

  redo: () =>
    set((s) => {
      if (s.future.length === 0) return {}
      const next = s.future[0]
      return {
        past: [...s.past, cloneReport(s.report)].slice(-50),
        future: s.future.slice(1),
        report: next,
      }
    }),

  // ---- DAX ----
  selectMeasure: (id) => set({ selectedMeasureId: id }),

  addMeasure: () =>
    set((s) => {
      const target =
        s.model.tables.find((t) => t.role === 'fact') ?? s.model.tables[0]
      if (!target) return {}
      const id = `m_${Date.now().toString(36)}`
      const measure: Measure = {
        id,
        name: 'New Measure',
        expression: 'SUM( )',
        formatString: '#,##0',
        displayFolder: 'Custom',
        description: '',
        isAutoGenerated: false,
      }
      return {
        model: {
          ...s.model,
          tables: s.model.tables.map((t) =>
            t.id === target.id ? { ...t, measures: [...t.measures, measure] } : t,
          ),
        },
        selectedMeasureId: id,
      }
    }),

  updateMeasure: (id, patch) =>
    set((s) => ({
      model: {
        ...s.model,
        tables: s.model.tables.map((t) => ({
          ...t,
          measures: t.measures.map((m) => (m.id === id ? { ...m, ...patch } : m)),
        })),
      },
    })),

  deleteMeasure: (id) =>
    set((s) => ({
      selectedMeasureId: s.selectedMeasureId === id ? null : s.selectedMeasureId,
      model: {
        ...s.model,
        tables: s.model.tables.map((t) => ({
          ...t,
          measures: t.measures.filter((m) => m.id !== id),
        })),
      },
    })),

  // ---- export ----
  toggleExport: (open) => set((s) => ({ exportOpen: open ?? !s.exportOpen })),

  // ---- plugins ----
  togglePlugins: (open) => set((s) => ({ pluginsOpen: open ?? !s.pluginsOpen })),

  // ---- analyst ----
  toggleAnalyst: (open) => set((s) => ({ analystOpen: open ?? !s.analystOpen })),

  askAnalyst: async (question) => {
    const q = question.trim()
    if (!q) return
    set((s) => ({
      analystOpen: true,
      analystThinking: true,
      analystMessages: [...s.analystMessages, { id: `msg_${msgSeq++}`, role: 'user', text: q }],
    }))
    const { model, datasets } = get()
    const turn = await services.analyst().ask(q, { model, datasets })
    set((s) => ({
      analystThinking: false,
      analystMessages: [
        ...s.analystMessages,
        { id: `msg_${msgSeq++}`, role: 'assistant', text: turn.text, chips: turn.chips },
      ],
    }))
  },
}))
