import { create } from 'zustand'
import type { Measure, Relationship, SemanticModel, Table } from '@/domain/model'
import { emptyModel } from '@/domain/model'
import type { Rect, Report, Visual } from '@/domain/report'
import { emptyReport } from '@/domain/report'
import type { DatasetData } from '@/application/import/types'
import { buildModel } from '@/application/model/auto-model'
import { generateLayout, DEFAULT_LAYOUT } from '@/application/insights/dashboard-generator'
import type { VisualSpec } from '@/application/insights/dashboard-generator'
import { generateDaxFromNL } from '@/application/dax/nl-templates'
import { architectSolution } from '@/application/dax/architect/architect'
import { parsePbipFolder, parsePbixFile, pbipSummary } from '@/application/import/pbi/open-project'
import { assemblePbiProject } from '@/application/import/pbi/assemble'
import type { ParsedDataset } from '@/application/import/types'
import type { PbiModel } from '@/application/import/pbi/tmdl'
import { probeDesktop, getDesktopModel, desktopRunDax, modelLabel, configureBridge, LOCAL_BRIDGE } from '@/infrastructure/desktop/desktop-client'
import type { DesktopStatus } from '@/infrastructure/desktop/desktop-client'
import { mapTmdlType } from '@/application/import/pbi/tmdl'
import { inferDataset } from '@/application/import/infer-schema'

/** Staged PBIP import — the user reviews per-table sources before committing. */
export interface PendingPbip {
  model: PbiModel
  real: Record<string, ParsedDataset> // tableName(lower) → bound real rows (auto + user)
  boundFrom: Record<string, string> // tableName(lower) → file it was bound from
}
import { resetAccent } from '@/design-system/runtime-theme'
import { services } from './services'

export interface PendingTable {
  id: string
  name: string
  rowCount: number
  columnCount: number
  table: Table
  data: DatasetData
}

export interface PendingImport {
  tables: PendingTable[]
  relationships: number
  fileNames: string[]
  currentTables: number
  currentMeasures: number
}

/** A remembered remote bridge, restored before the first probe so a reload
 * reconnects to the same machine instead of silently falling back to this one. */
const BRIDGE_KEY = 'pbistudio.bridge.v1'
const savedBridge: { url: string; token: string | null } = (() => {
  try {
    const raw = localStorage.getItem(BRIDGE_KEY)
    if (raw) {
      const v = JSON.parse(raw) as { url?: string; token?: string | null }
      if (v.url) return { url: v.url, token: v.token ?? null }
    }
  } catch { /* private mode, corrupt value — fall back to local */ }
  return { url: LOCAL_BRIDGE, token: null }
})()
configureBridge(savedBridge.url, savedBridge.token)

function persistBridge(url: string, token: string | null): void {
  try {
    if (url === LOCAL_BRIDGE && !token) localStorage.removeItem(BRIDGE_KEY)
    else localStorage.setItem(BRIDGE_KEY, JSON.stringify({ url, token }))
  } catch { /* nothing we can do, and not worth failing the connect over */ }
}

/** Run the auto-model engine over the current datasets + tables. */
function analyze(
  datasets: DatasetData[],
  tables: Table[],
): { tables: Table[]; relationships: Relationship[] } {
  const inputs = datasets
    .map((data) => {
      const table = tables.find((t) => t.id === data.id)
      return table ? { data, table } : null
    })
    .filter((x): x is { data: DatasetData; table: Table } => x !== null)
  if (inputs.length === 0) return { tables, relationships: [] }
  const res = buildModel(inputs)
  return { tables: res.tables, relationships: res.relationships }
}

/** Generate measures + a dashboard (in the chosen layout); attach measures to tables. */
function buildArtifacts(model: SemanticModel, layoutId: string): { model: SemanticModel; report: Report } {
  const { page, measures } = generateLayout(model, layoutId)
  const tables = model.tables.map((t) => {
    const measuresForTable: Measure[] = measures
      .filter((m) => m.tableId === t.id)
      .map((m) => ({
        id: m.id,
        name: m.name,
        expression: m.dax.includes(' = ') ? m.dax.split(' = ').slice(1).join(' = ') : m.dax,
        formatString: m.formatString,
        displayFolder: m.displayFolder,
        description: `Auto-generated ${m.kind} measure`,
        confidence: m.confidence,
        isAutoGenerated: true,
      }))
    return { ...t, measures: measuresForTable }
  })
  const report: Report = {
    id: 'report',
    name: 'Report',
    pages: [page],
    activePageId: page.id,
    themeId: 'studio',
  }
  return { model: { ...model, tables }, report }
}

export type View = 'home' | 'studio'
export type Theme = 'light' | 'dark'
export type StudioMode = 'kpi' | 'design' | 'data' | 'model' | 'cleanup' | 'dax'

interface PanelState {
  left: boolean
  right: boolean
  bottom: boolean
}

interface AppState {
  view: View
  theme: Theme
  mode: StudioMode
  panels: PanelState
  /** Which tab the bottom panel shows — lifted here so a KPI card click can
   * jump straight to the DAX tab. */
  bottomTab: 'insights' | 'dax' | 'data'
  commandPaletteOpen: boolean
  projectName: string | null
  layoutId: string
  layoutChooserOpen: boolean

  // ---- document state ----
  model: SemanticModel
  report: Report
  datasets: DatasetData[]
  activeDatasetId: string | null

  // ---- designer ----
  selectedVisualId: string | null
  past: Report[]
  future: Report[]

  // ---- DAX ----
  selectedMeasureId: string | null

  // ---- analyst ----
  analystOpen: boolean
  analystThinking: boolean
  analystMessages: AnalystMessage[]

  // ---- plugins ----
  pluginsOpen: boolean

  // ---- import ----
  importing: boolean
  importError: string | null
  importNote: string | null
  pbixFallback: { message: string; pages: number } | null
  pendingImport: PendingImport | null
  pendingPbip: PendingPbip | null
  desktop: DesktopStatus
  /** Where the bridge lives. Remote = another machine, reached with a token. */
  bridgeUrl: string
  bridgeToken: string | null
  remoteOpen: boolean
  refreshDesktop: () => Promise<void>
  syncFromDesktop: () => Promise<void>
  setBridge: (url: string, token: string | null) => Promise<void>
  toggleRemote: (open?: boolean) => void
  factoryOpen: boolean
  doctorOpen: boolean
  dateTableOpen: boolean
  /** KPI board slot overrides (index -> measure name, null = cleared). Slots
   * without an override auto-fill newest-first. */
  kpiOverrides: Record<number, string | null>
  answersMatrix: { row: string | null; col: string | null; values: string[] }
  answersTable: { dims: string[]; values: string[] }
  /** Zoom factor for the KPI surface (1 = 100%). */
  kpiZoom: number
  setKpiSlot: (index: number, measureName: string | null) => void
  setKpiZoom: (zoom: number) => void
  setAnswersMatrix: (cfg: Partial<{ row: string | null; col: string | null; values: string[] }>) => void
  setAnswersTable: (cfg: Partial<{ dims: string[]; values: string[] }>) => void
  toggleFactory: (open?: boolean) => void
  toggleDoctor: (open?: boolean) => void
  toggleDateTable: (open?: boolean) => void
  /** Cleanup surface — object keys staged for deletion. This is a STAGING
   * area only: nothing reaches the real model until an explicit Deploy, so
   * undo/redo here is free and unlimited. */
  cleanupStaged: string[]
  cleanupUndo: string[][]
  cleanupRedo: string[][]
  toggleCleanupStage: (key: string) => void
  stageCleanup: (keys: string[]) => void
  clearCleanupStage: () => void
  undoCleanup: () => void
  redoCleanup: () => void
  _pickFiles: (() => void) | null
  _pickPbip: (() => void) | null
  _pickPbix: (() => void) | null

  // ---- actions ----
  goHome: () => void
  openStudio: (projectName: string) => void
  setMode: (mode: StudioMode) => void
  toggleTheme: () => void
  setTheme: (t: Theme) => void
  togglePanel: (panel: keyof PanelState) => void
  setBottomTab: (tab: 'insights' | 'dax' | 'data') => void
  setCommandPalette: (open: boolean) => void

  registerFilePicker: (fn: () => void) => void
  registerPbipPicker: (fn: () => void) => void
  registerPbixPicker: (fn: () => void) => void
  requestImport: () => void
  requestOpenPbip: () => void
  requestOpenPbix: () => void
  openPbipFiles: (files: File[]) => Promise<void>
  bindPbipTable: (tableName: string, file: File) => Promise<void>
  bindPbipTableCsv: (tableName: string, csvText: string) => Promise<void>
  unbindPbipTable: (tableName: string) => void
  commitPbip: () => void
  cancelPbip: () => void
  openPbixFile: (file: File) => Promise<void>
  importFiles: (files: File[]) => Promise<void>
  stageImport: (files: File[]) => Promise<void>
  commitImport: (selectedIds: string[], mode: 'replace' | 'merge') => void
  cancelImport: () => void
  setActiveDataset: (id: string) => void
  dismissImportError: () => void
  dismissImportNote: () => void
  dismissPbixFallback: () => void
  runAutoModel: () => void
  generateDashboard: () => void
  applyLayout: (layoutId: string) => void
  toggleLayoutChooser: (open?: boolean) => void

  // designer actions
  selectVisual: (id: string | null) => void
  beginChange: () => void
  setVisualRect: (id: string, rect: Rect) => void
  updateVisual: (id: string, patch: Partial<Visual>) => void
  setVisualSpec: (id: string, spec: VisualSpec, title?: string) => void
  addVisual: (visual: Visual) => void
  duplicateVisual: (id: string) => void
  deleteVisual: (id: string) => void
  nudgeVisual: (id: string, dx: number, dy: number) => void
  undo: () => void
  redo: () => void

  // DAX actions
  selectMeasure: (id: string | null) => void
  /** Focus a measure in the bottom DAX inspector: selects it, switches the
   * bottom panel to the DAX tab, and opens the panel if it's collapsed. */
  inspectMeasure: (id: string) => void
  addMeasure: () => void
  updateMeasure: (id: string, patch: Partial<Measure>) => void
  deleteMeasure: (id: string) => void
  generateMeasure: (prompt: string) => { measureId: string; explanation: string; steps?: string[]; plan?: { stepNumber: number; name: string; dax: string; reason: string }[]; validationErrors?: string[] } | null
  commitMeasures: (steps: { name: string; dax: string }[], finalName: string, formatString?: string) => string | null

  // analyst actions
  toggleAnalyst: (open?: boolean) => void
  askAnalyst: (question: string) => Promise<void>

  // plugins
  togglePlugins: (open?: boolean) => void
}

export interface AnalystMessage {
  id: string
  role: 'user' | 'assistant'
  text: string
  chips?: string[]
}

let msgSeq = 0

const cloneReport = (r: Report): Report => structuredClone(r)

/** Replace the active page's visuals immutably. */
function withVisuals(report: Report, fn: (v: Visual[]) => Visual[]): Report {
  return {
    ...report,
    pages: report.pages.map((p) =>
      p.id === (report.activePageId ?? report.pages[0]?.id)
        ? { ...p, visuals: fn(p.visuals) }
        : p,
    ),
  }
}

const applyTheme = (t: Theme) => {
  document.documentElement.setAttribute('data-theme', t)
  try {
    localStorage.setItem('pbs.theme', t)
  } catch {
    /* storage may be unavailable — non-fatal */
  }
}

const initialTheme: Theme =
  (document.documentElement.getAttribute('data-theme') as Theme) || 'light'

/** Ensure a dataset id is unique against existing + newly-added datasets. */
function uniqueId(base: string, taken: Set<string>): string {
  if (!taken.has(base)) return base
  let n = 2
  while (taken.has(`${base}_${n}`)) n++
  return `${base}_${n}`
}

export const useApp = create<AppState>((set, get) => ({
  view: 'home',
  theme: initialTheme,
  mode: 'kpi',
  panels: { left: true, right: true, bottom: false },
  bottomTab: 'insights',
  commandPaletteOpen: false,
  projectName: null,
  layoutId: DEFAULT_LAYOUT,
  layoutChooserOpen: false,

  model: emptyModel('model', 'Model'),
  report: emptyReport('report', 'Report'),
  datasets: [],
  activeDatasetId: null,

  selectedVisualId: null,
  past: [],
  future: [],

  selectedMeasureId: null,

  analystOpen: false,
  analystThinking: false,
  analystMessages: [],

  pluginsOpen: false,

  importing: false,
  importError: null,
  importNote: null,
  pbixFallback: null,
  pendingImport: null,
  pendingPbip: null,
  desktop: { bridge: false, connected: false },
  bridgeUrl: savedBridge.url,
  bridgeToken: savedBridge.token,
  remoteOpen: false,
  factoryOpen: false,
  doctorOpen: false,
  dateTableOpen: false,
  kpiOverrides: {},
  answersMatrix: { row: null, col: null, values: [] },
  answersTable: { dims: [], values: [] },
  kpiZoom: 1,
  _pickFiles: null,
  _pickPbip: null,
  _pickPbix: null,

  goHome: () => set({ view: 'home' }),

  openStudio: (projectName) => set({ view: 'studio', projectName, mode: 'kpi' }),

  setMode: (mode) => set({ mode }),

  toggleTheme: () => {
    const next: Theme = get().theme === 'light' ? 'dark' : 'light'
    applyTheme(next)
    set({ theme: next })
  },

  setTheme: (t) => {
    applyTheme(t)
    set({ theme: t })
  },

  togglePanel: (panel) =>
    set((s) => ({ panels: { ...s.panels, [panel]: !s.panels[panel] } })),

  setBottomTab: (tab) => set({ bottomTab: tab }),

  setCommandPalette: (open) => set({ commandPaletteOpen: open }),

  registerFilePicker: (fn) => set({ _pickFiles: fn }),
  registerPbipPicker: (fn) => set({ _pickPbip: fn }),
  registerPbixPicker: (fn) => set({ _pickPbix: fn }),

  requestImport: () => {
    const pick = get()._pickFiles
    if (pick) pick()
  },

  requestOpenPbip: () => {
    const pick = get()._pickPbip
    if (pick) pick()
  },

  requestOpenPbix: () => {
    const pick = get()._pickPbix
    if (pick) pick()
  },

  // Parse the project + auto-bind folder files, then open the source-review dialog.
  openPbipFiles: async (files) => {
    if (files.length === 0) return
    set({ importing: true, importError: null, importNote: null })
    try {
      const { model, dataFiles } = await parsePbipFolder(files)
      const real: Record<string, ParsedDataset> = {}
      const boundFrom: Record<string, string> = {}

      if (dataFiles && dataFiles.length) {
        const svc = services.import()
        const byFile: Record<string, { parsed: ParsedDataset; file: string }[]> = {}
        const byName: Record<string, { parsed: ParsedDataset; file: string }> = {}
        for (const file of dataFiles) {
          const res = await svc.importFile(file)
          if (!res.ok) continue
          const list = res.value.map((d) => ({
            parsed: { name: d.data.name, columns: d.data.columns, rows: d.data.rows, rowCount: d.data.rowCount },
            file: file.name,
          }))
          byFile[file.name.toLowerCase()] = list
          for (const it of list) byName[it.parsed.name.toLowerCase()] = it
        }
        for (const t of model.tables) {
          const nm = t.name.toLowerCase()
          if (byName[nm]) { real[nm] = byName[nm].parsed; boundFrom[nm] = byName[nm].file; continue }
          const f = t.source?.file?.toLowerCase()
          const hit = f ? byFile[f] : undefined
          if (hit && hit[0]) { real[nm] = hit[0].parsed; boundFrom[nm] = hit[0].file }
        }
      }

      set({ importing: false, pendingPbip: { model, real, boundFrom } })
    } catch (e) {
      set({ importing: false, importError: e instanceof Error ? e.message : 'Could not open the PBIP project.' })
    }
  },

  // Bind (or re-point) a table's real data by attaching a file.
  bindPbipTable: async (tableName, file) => {
    const res = await services.import().importFile(file)
    if (!res.ok || !res.value[0]) { set({ importError: res.ok ? 'No rows found in that file.' : res.error }); return }
    const d = res.value[0].data
    const key = tableName.toLowerCase()
    set((s) =>
      s.pendingPbip
        ? {
            importError: null,
            pendingPbip: {
              ...s.pendingPbip,
              real: { ...s.pendingPbip.real, [key]: { name: d.name, columns: d.columns, rows: d.rows, rowCount: d.rowCount } },
              boundFrom: { ...s.pendingPbip.boundFrom, [key]: file.name },
            },
          }
        : {},
    )
  },

  // Bind a table by pasting CSV text.
  bindPbipTableCsv: async (tableName, csvText) => {
    if (!csvText.trim()) return
    const file = new File([csvText], `${tableName}.csv`, { type: 'text/csv' })
    await get().bindPbipTable(tableName, file)
  },

  unbindPbipTable: (tableName) =>
    set((s) => {
      if (!s.pendingPbip) return {}
      const key = tableName.toLowerCase()
      const real = { ...s.pendingPbip.real }
      const boundFrom = { ...s.pendingPbip.boundFrom }
      delete real[key]
      delete boundFrom[key]
      return { pendingPbip: { ...s.pendingPbip, real, boundFrom } }
    }),

  commitPbip: () => {
    const s = get()
    const p = s.pendingPbip
    if (!p) return
    const load = assemblePbiProject(p.model, s.layoutId, p.real)
    resetAccent()
    set({
      view: 'studio',
      mode: 'kpi',
      datasets: load.datasets,
      model: load.model,
      report: load.report,
      activeDatasetId: load.datasets[0]?.id ?? null,
      projectName: p.model.name,
          importing: false,
      importError: null,
      importNote: pbipSummary(p.model, load.realCount),
      pendingPbip: null,
      selectedVisualId: null,
      selectedMeasureId: null,
      past: [],
      future: [],
    })
  },

  cancelPbip: () => set({ pendingPbip: null }),

  refreshDesktop: async () => set({ desktop: await probeDesktop() }),

  setBridge: async (url, token) => {
    const clean = (url || LOCAL_BRIDGE).replace(/\/+$/, '')
    configureBridge(clean, token)
    persistBridge(clean, token)
    set({ bridgeUrl: clean, bridgeToken: token, remoteOpen: false })
    await get().refreshDesktop()
  },
  toggleRemote: (open) => set((s) => ({ remoteOpen: open ?? !s.remoteOpen })),
  toggleFactory: (open) => set((s) => ({ factoryOpen: open ?? !s.factoryOpen })),
  toggleDoctor: (open) => set((s) => ({ doctorOpen: open ?? !s.doctorOpen })),
  toggleDateTable: (open) => set((s) => ({ dateTableOpen: open ?? !s.dateTableOpen })),
  cleanupStaged: [],
  cleanupUndo: [],
  cleanupRedo: [],
  toggleCleanupStage: (key) =>
    set((s) => ({
      cleanupStaged: s.cleanupStaged.includes(key)
        ? s.cleanupStaged.filter((k) => k !== key)
        : [...s.cleanupStaged, key],
      cleanupUndo: [...s.cleanupUndo, s.cleanupStaged],
      cleanupRedo: [],
    })),
  stageCleanup: (keys) =>
    set((s) => ({
      cleanupStaged: [...new Set([...s.cleanupStaged, ...keys])],
      cleanupUndo: [...s.cleanupUndo, s.cleanupStaged],
      cleanupRedo: [],
    })),
  clearCleanupStage: () =>
    set((s) => ({ cleanupStaged: [], cleanupUndo: [...s.cleanupUndo, s.cleanupStaged], cleanupRedo: [] })),
  undoCleanup: () =>
    set((s) => {
      if (s.cleanupUndo.length === 0) return {}
      const prev = s.cleanupUndo[s.cleanupUndo.length - 1]
      return {
        cleanupStaged: prev,
        cleanupUndo: s.cleanupUndo.slice(0, -1),
        cleanupRedo: [...s.cleanupRedo, s.cleanupStaged],
      }
    }),
  redoCleanup: () =>
    set((s) => {
      if (s.cleanupRedo.length === 0) return {}
      const next = s.cleanupRedo[s.cleanupRedo.length - 1]
      return {
        cleanupStaged: next,
        cleanupUndo: [...s.cleanupUndo, s.cleanupStaged],
        cleanupRedo: s.cleanupRedo.slice(0, -1),
      }
    }),
  setKpiSlot: (index, measureName) => set((s) => ({ kpiOverrides: { ...s.kpiOverrides, [index]: measureName } })),
  setKpiZoom: (zoom) => set({ kpiZoom: Math.min(1.5, Math.max(0.5, Math.round(zoom * 100) / 100)) }),
  setAnswersMatrix: (cfg) => set((s) => ({ answersMatrix: { ...s.answersMatrix, ...cfg } })),
  setAnswersTable: (cfg) => set((s) => ({ answersTable: { ...s.answersTable, ...cfg } })),

  // Pull the REAL model + data from the connected Power BI Desktop into the Studio.
  syncFromDesktop: async () => {
    const s = get()
    if (!s.desktop.connected) { set({ importError: 'Connect to Power BI Desktop first (open a .pbix).' }); return }
    set({ importing: true, importError: null, importNote: null })
    try {
      const dm = await getDesktopModel(s.desktop.port)
      const pbi: PbiModel = {
        name: modelLabel(dm.database) ?? 'Power BI model',
        tables: dm.tables.map((t) => ({
          name: t.name,
          isHidden: t.isHidden,
          columns: t.columns.map((c) => ({ name: c.name, dataType: mapTmdlType(c.dataType) })),
          measures: t.measures.map((m) => ({ name: m.name, expression: m.expression, formatString: m.formatString, displayFolder: m.displayFolder })),
        })),
        relationships: dm.relationships.map((r) => ({
          fromTable: r.fromTable, fromColumn: r.fromColumn, toTable: r.toTable, toColumn: r.toColumn,
          isActive: r.isActive, crossFilter: 'single' as const,
        })),
      }

      // Pull real rows per data table via EVALUATE (capped by the bridge).
      const realByName: Record<string, ParsedDataset> = {}
      for (const t of dm.tables) {
        if (t.columns.length === 0) continue
        try {
          const q = await desktopRunDax(`EVALUATE '${t.name.replace(/'/g, "''")}'`, s.desktop.port)
          if (q.rows.length === 0) continue
          const headers = q.columns.map((c) => (c.includes('[') ? c.slice(c.indexOf('[') + 1, -1) : c))
          const raw = q.rows.map((r) => q.columns.map((c) => (r[c] == null ? '' : String(r[c]))))
          realByName[t.name.toLowerCase()] = inferDataset(t.name, headers, raw)
        } catch {
          /* table not queryable (calc group / empty) — skip, uses sample */
        }
      }

      const load = assemblePbiProject(pbi, s.layoutId, realByName)
      resetAccent()
      const measureCount = pbi.tables.reduce((n, t) => n + t.measures.length, 0)
      set({
        view: 'studio',
        mode: 'kpi',
        datasets: load.datasets,
        model: load.model,
        report: load.report,
        activeDatasetId: load.datasets[0]?.id ?? null,
        projectName: modelLabel(dm.database) ?? 'Power BI Desktop model',
              importing: false,
        importError: null,
        importNote: `Synced from Power BI Desktop — ${dm.tables.length} tables (real data), ${measureCount} live measures. Previews now run on your real model.`,
        selectedVisualId: null,
        selectedMeasureId: null,
        past: [],
        future: [],
      })
    } catch (e) {
      set({ importing: false, importError: e instanceof Error ? e.message : 'Sync from Desktop failed.' })
    }
  },

  openPbixFile: async (file) => {
    set({ importing: true, importError: null, importNote: null, pbixFallback: null })
    try {
      const result = await parsePbixFile(file)
      if ('fallback' in result) {
        set({ importing: false, pbixFallback: { message: result.fallback, pages: result.pages } })
        return
      }
      const { model, note } = result
      const load = assemblePbiProject(model, get().layoutId)
      resetAccent()
      set({
        view: 'studio',
        mode: 'kpi',
        datasets: load.datasets,
        model: load.model,
        report: load.report,
        activeDatasetId: load.datasets[0]?.id ?? null,
        projectName: model.name,
              importing: false,
        importError: null,
        importNote: note,
        selectedVisualId: null,
        selectedMeasureId: null,
        past: [],
        future: [],
      })
    } catch (e) {
      set({ importing: false, importError: e instanceof Error ? e.message : 'Could not open the PBIX file.' })
    }
  },

  importFiles: async (files) => {
    if (files.length === 0) return
    set({ importing: true, importError: null })

    const svc = services.import()
    const taken = new Set(get().datasets.map((d) => d.id))
    const addedData: DatasetData[] = []
    const addedTables: SemanticModel['tables'] = []
    let firstId: string | null = null
    let error: string | null = null

    for (const file of files) {
      const res = await svc.importFile(file)
      if (res.ok) {
        for (const imported of res.value) {
          const id = uniqueId(imported.data.id, taken)
          taken.add(id)
          const data = { ...imported.data, id }
          // Re-base column ids onto the final (deduped) table id.
          const columns = imported.table.columns.map((c) => ({
            ...c,
            id: `${id}::${c.id.split('::').pop() ?? c.name}`,
          }))
          const table = { ...imported.table, id, columns }
          addedData.push(data)
          addedTables.push(table)
          firstId ??= id
        }
      } else {
        error = res.error
      }
    }

    set((s) => {
      const datasets = [...s.datasets, ...addedData]
      const mergedTables = [...s.model.tables, ...addedTables]
      const analyzed = analyze(datasets, mergedTables)
      const modeled: SemanticModel = {
        ...s.model,
        tables: analyzed.tables,
        relationships: analyzed.relationships,
      }
      const artifacts = buildArtifacts(modeled, s.layoutId)
      const hasDashboard = (artifacts.report.pages[0]?.visuals.length ?? 0) > 0
      const imported = addedData.length > 0
      return {
        datasets,
        model: artifacts.model,
        report: artifacts.report,
        activeDatasetId: firstId ?? s.activeDatasetId,
        importing: false,
        importError: error,
        view: imported ? 'studio' : s.view,
        mode: imported ? 'kpi' : s.mode,
        projectName: s.projectName ?? addedData[0]?.name ?? null,
        selectedVisualId: null,
        past: [],
        future: [],
      }
    })
  },

  // Parse files and open the confirmation dialog (no commit yet).
  stageImport: async (files) => {
    if (files.length === 0) return
    set({ importing: true, importError: null })

    const svc = services.import()
    const taken = new Set<string>()
    const pendingTables: PendingTable[] = []
    let error: string | null = null

    for (const file of files) {
      const res = await svc.importFile(file)
      if (res.ok) {
        for (const imported of res.value) {
          const id = uniqueId(imported.data.id, taken)
          taken.add(id)
          const data = { ...imported.data, id }
          const columns = imported.table.columns.map((c) => ({
            ...c,
            id: `${id}::${c.id.split('::').pop() ?? c.name}`,
          }))
          const table = { ...imported.table, id, columns }
          pendingTables.push({
            id,
            name: table.name,
            rowCount: data.rowCount,
            columnCount: data.columns.length,
            table,
            data,
          })
        }
      } else {
        error = res.error
      }
    }

    if (pendingTables.length === 0) {
      set({ importing: false, importError: error ?? 'Nothing to import.' })
      return
    }

    const preview = buildModel(pendingTables.map((p) => ({ table: p.table, data: p.data })))
    const s = get()
    set({
      importing: false,
      importError: error,
      pendingImport: {
        tables: pendingTables,
        relationships: preview.relationships.filter((r) => r.isActive).length,
        fileNames: [...new Set(files.map((f) => f.name))],
        currentTables: s.datasets.length,
        currentMeasures: s.model.tables.reduce((n, t) => n + t.measures.length, 0),
      },
    })
  },

  commitImport: (selectedIds, mode) =>
    set((s) => {
      const pending = s.pendingImport
      if (!pending) return {}
      const selected = pending.tables.filter((t) => selectedIds.includes(t.id))
      if (selected.length === 0) return { pendingImport: null }

      let datasets: DatasetData[]
      let tables: Table[]

      if (mode === 'merge') {
        const taken = new Set(s.datasets.map((d) => d.id))
        const addData: DatasetData[] = []
        const addTables: Table[] = []
        for (const p of selected) {
          const id = uniqueId(p.id, taken)
          taken.add(id)
          addData.push({ ...p.data, id })
          addTables.push({
            ...p.table,
            id,
            columns: p.table.columns.map((c) => ({ ...c, id: `${id}::${c.id.split('::').pop() ?? c.name}` })),
          })
        }
        datasets = [...s.datasets, ...addData]
        tables = [...s.model.tables, ...addTables]
      } else {
        datasets = selected.map((p) => p.data)
        tables = selected.map((p) => p.table)
      }

      const analyzed = analyze(datasets, tables)
      const baseModel: SemanticModel =
        mode === 'merge'
          ? { ...s.model, tables: analyzed.tables, relationships: analyzed.relationships }
          : { ...emptyModel('model', 'Model'), tables: analyzed.tables, relationships: analyzed.relationships }
      const artifacts = buildArtifacts(baseModel, s.layoutId)
      const hasDashboard = (artifacts.report.pages[0]?.visuals.length ?? 0) > 0

      if (mode === 'replace') resetAccent()

      return {
        datasets,
        model: artifacts.model,
        report: artifacts.report,
        activeDatasetId: datasets[0]?.id ?? null,
        projectName:
          mode === 'replace'
            ? pending.fileNames[0]?.replace(/\.[^.]+$/, '') ?? selected[0]?.name ?? 'Imported'
            : s.projectName,
        view: 'studio',
        mode: 'kpi',
        pendingImport: null,
        selectedVisualId: null,
        selectedMeasureId: null,
        past: [],
        future: [],
      }
    }),

  cancelImport: () => set({ pendingImport: null }),

  setActiveDataset: (id) => set({ activeDatasetId: id, mode: 'data' }),

  dismissImportError: () => set({ importError: null }),
  dismissImportNote: () => set({ importNote: null }),
  dismissPbixFallback: () => set({ pbixFallback: null }),

  runAutoModel: () =>
    set((s) => {
      const analyzed = analyze(s.datasets, s.model.tables)
      const modeled: SemanticModel = {
        ...s.model,
        tables: analyzed.tables,
        relationships: analyzed.relationships,
      }
      const artifacts = buildArtifacts(modeled, s.layoutId)
      return { model: artifacts.model, report: artifacts.report }
    }),

  generateDashboard: () =>
    set((s) => {
      const artifacts = buildArtifacts(s.model, s.layoutId)
      return {
        model: artifacts.model,
        report: artifacts.report,
        mode: 'kpi',
        selectedVisualId: null,
        past: [],
        future: [],
      }
    }),

  applyLayout: (layoutId) =>
    set((s) => {
      const artifacts = buildArtifacts(s.model, layoutId)
      return {
        layoutId,
        model: artifacts.model,
        report: artifacts.report,
        mode: 'kpi',
        selectedVisualId: null,
        past: [],
        future: [],
      }
    }),

  toggleLayoutChooser: (open) => set((s) => ({ layoutChooserOpen: open ?? !s.layoutChooserOpen })),

  // ---- designer ----
  selectVisual: (id) => set({ selectedVisualId: id }),

  beginChange: () =>
    set((s) => ({ past: [...s.past, cloneReport(s.report)].slice(-50), future: [] })),

  setVisualRect: (id, rect) =>
    set((s) => ({
      report: withVisuals(s.report, (vs) => vs.map((v) => (v.id === id ? { ...v, rect } : v))),
    })),

  updateVisual: (id, patch) =>
    set((s) => ({
      report: withVisuals(s.report, (vs) => vs.map((v) => (v.id === id ? { ...v, ...patch } : v))),
    })),

  setVisualSpec: (id, spec, title) =>
    set((s) => ({
      past: [...s.past, cloneReport(s.report)].slice(-50),
      future: [],
      report: withVisuals(s.report, (vs) =>
        vs.map((v) =>
          v.id === id
            ? { ...v, title: title ?? v.title, style: { ...(v.style as object), spec } }
            : v,
        ),
      ),
    })),

  addVisual: (visual) =>
    set((s) => ({
      past: [...s.past, cloneReport(s.report)].slice(-50),
      future: [],
      report: withVisuals(s.report, (vs) => [...vs, visual]),
      selectedVisualId: visual.id,
    })),

  duplicateVisual: (id) =>
    set((s) => {
      const page = s.report.pages.find((p) => p.id === s.report.activePageId) ?? s.report.pages[0]
      const src = page?.visuals.find((v) => v.id === id)
      if (!src) return {}
      const copy: Visual = {
        ...structuredClone(src),
        id: `v_${Date.now().toString(36)}`,
        rect: { ...src.rect, x: src.rect.x + 24, y: src.rect.y + 24 },
      }
      return {
        past: [...s.past, cloneReport(s.report)].slice(-50),
        future: [],
        report: withVisuals(s.report, (vs) => [...vs, copy]),
        selectedVisualId: copy.id,
      }
    }),

  deleteVisual: (id) =>
    set((s) => ({
      past: [...s.past, cloneReport(s.report)].slice(-50),
      future: [],
      report: withVisuals(s.report, (vs) => vs.filter((v) => v.id !== id)),
      selectedVisualId: s.selectedVisualId === id ? null : s.selectedVisualId,
    })),

  nudgeVisual: (id, dx, dy) =>
    set((s) => ({
      past: [...s.past, cloneReport(s.report)].slice(-50),
      future: [],
      report: withVisuals(s.report, (vs) =>
        vs.map((v) =>
          v.id === id
            ? { ...v, rect: { ...v.rect, x: Math.max(0, v.rect.x + dx), y: Math.max(0, v.rect.y + dy) } }
            : v,
        ),
      ),
    })),

  undo: () =>
    set((s) => {
      if (s.past.length === 0) return {}
      const previous = s.past[s.past.length - 1]
      return {
        past: s.past.slice(0, -1),
        future: [cloneReport(s.report), ...s.future].slice(0, 50),
        report: previous,
      }
    }),

  redo: () =>
    set((s) => {
      if (s.future.length === 0) return {}
      const next = s.future[0]
      return {
        past: [...s.past, cloneReport(s.report)].slice(-50),
        future: s.future.slice(1),
        report: next,
      }
    }),

  // ---- DAX ----
  selectMeasure: (id) => set({ selectedMeasureId: id }),

  inspectMeasure: (id) =>
    set((s) => ({
      selectedMeasureId: id,
      selectedVisualId: null,
      bottomTab: 'dax',
      panels: { ...s.panels, bottom: true },
    })),

  addMeasure: () =>
    set((s) => {
      const target =
        s.model.tables.find((t) => t.role === 'fact') ?? s.model.tables[0]
      if (!target) return {}
      const id = `m_${Date.now().toString(36)}`
      const measure: Measure = {
        id,
        name: 'New Measure',
        expression: 'SUM( )',
        formatString: '#,##0',
        displayFolder: 'Custom',
        description: '',
        isAutoGenerated: false,
      }
      return {
        model: {
          ...s.model,
          tables: s.model.tables.map((t) =>
            t.id === target.id ? { ...t, measures: [...t.measures, measure] } : t,
          ),
        },
        selectedMeasureId: id,
      }
    }),

  updateMeasure: (id, patch) =>
    set((s) => ({
      model: {
        ...s.model,
        tables: s.model.tables.map((t) => ({
          ...t,
          measures: t.measures.map((m) => (m.id === id ? { ...m, ...patch } : m)),
        })),
      },
    })),

  deleteMeasure: (id) =>
    set((s) => ({
      selectedMeasureId: s.selectedMeasureId === id ? null : s.selectedMeasureId,
      model: {
        ...s.model,
        tables: s.model.tables.map((t) => ({
          ...t,
          measures: t.measures.filter((m) => m.id !== id),
        })),
      },
    })),

  generateMeasure: (prompt) => {
    const s = get()

    // ---- deterministic DAX Architect engine (measure branching) ----
    const sol = architectSolution(s.model, prompt, s.datasets)
    const measureSteps = sol?.steps?.filter((st) => st.objectType === 'Measure') ?? []
    if (sol && measureSteps.length > 0) {
      const tablesCopy = s.model.tables.map((t) => ({ ...t, measures: [...t.measures] }))
      const fact = tablesCopy.find((t) => t.role === 'fact') ?? tablesCopy[0]
      const idByName = new Map<string, string>()
      for (const t of tablesCopy) for (const m of t.measures) idByName.set(m.name.toLowerCase(), m.id)
      let seq = get().datasets.length + 1

      for (const st of measureSteps) {
        const key = st.name.toLowerCase()
        const existingId = idByName.get(key)
        if (existingId) {
          for (const t of tablesCopy)
            t.measures = t.measures.map((m) =>
              m.id === existingId
                ? { ...m, expression: st.dax, formatString: st.formatString ?? m.formatString, displayFolder: st.displayFolder ?? m.displayFolder, description: st.reason ?? m.description }
                : m,
            )
        } else {
          const id = `m_${prompt.length}_${seq++}`
          const home = tablesCopy.find((t) => t.name === st.homeTable) ?? fact ?? tablesCopy[0]
          const measure: Measure = {
            id,
            name: st.name,
            expression: st.dax,
            formatString: st.formatString ?? '#,##0',
            displayFolder: st.displayFolder ?? 'Custom',
            description: st.reason ?? '',
            isAutoGenerated: false,
          }
          home.measures.push(measure)
          idByName.set(key, id)
        }
      }

      const finalId =
        idByName.get(sol.finalObject.name.toLowerCase()) ??
        idByName.get(measureSteps[measureSteps.length - 1].name.toLowerCase()) ??
        null
      if (finalId) {
        set({ model: { ...s.model, tables: tablesCopy }, selectedMeasureId: finalId })
        const errs = sol.validationErrors ?? []
        const explanation = (errs.length ? '⚠ ' + errs.join(' ') + '  ' : '') + sol.goalRestatement
        return {
          measureId: finalId,
          explanation,
          steps: measureSteps.map((st) => st.name),
          plan: measureSteps.map((st) => ({ stepNumber: st.stepNumber, name: st.name, dax: st.dax, reason: st.reason })),
          validationErrors: errs,
        }
      }
    }

    // ---- fallback: single-measure heuristic ----
    const g = generateDaxFromNL(prompt, s.model, s.datasets)
    if (!g) return null
    const target = s.model.tables.find((t) => t.role === 'fact') ?? s.model.tables[0]
    if (!target) return null
    // Upsert by name so repeated generations don't create duplicate measures.
    const existing = s.model.tables.flatMap((t) => t.measures).find((m) => m.name.toLowerCase() === g.name.toLowerCase())
    if (existing) {
      set({
        selectedMeasureId: existing.id,
        model: {
          ...s.model,
          tables: s.model.tables.map((t) => ({
            ...t,
            measures: t.measures.map((m) => (m.id === existing.id ? { ...m, expression: g.expression, formatString: g.formatString } : m)),
          })),
        },
      })
      return { measureId: existing.id, explanation: g.explanation }
    }
    const id = `m_${Date.now().toString(36)}`
    const measure: Measure = { id, name: g.name, expression: g.expression, formatString: g.formatString, displayFolder: 'Custom', description: '', isAutoGenerated: false }
    set({
      selectedMeasureId: id,
      model: { ...s.model, tables: s.model.tables.map((t) => (t.id === target.id ? { ...t, measures: [...t.measures, measure] } : t)) },
    })
    return { measureId: id, explanation: g.explanation }
  },

  // Upsert a set of measures (a suggestion's plan) by name, select the final.
  commitMeasures: (steps, finalName, formatString) => {
    const s = get()
    if (steps.length === 0) return null
    const tablesCopy = s.model.tables.map((t) => ({ ...t, measures: [...t.measures] }))
    const home = tablesCopy.find((t) => t.role === 'fact') ?? tablesCopy[0]
    if (!home) return null
    const idByName = new Map<string, string>()
    for (const t of tablesCopy) for (const m of t.measures) idByName.set(m.name.toLowerCase(), m.id)
    let seq = get().datasets.length + 1

    for (const st of steps) {
      const key = st.name.toLowerCase()
      const existingId = idByName.get(key)
      const isFinal = st.name === finalName
      if (existingId) {
        for (const t of tablesCopy)
          t.measures = t.measures.map((m) =>
            m.id === existingId ? { ...m, expression: st.dax, formatString: isFinal ? formatString ?? m.formatString : m.formatString } : m,
          )
      } else {
        const id = `m_commit_${seq++}_${st.name.length}`
        home.measures.push({
          id,
          name: st.name,
          expression: st.dax,
          formatString: isFinal ? formatString ?? '#,##0' : '#,##0',
          displayFolder: 'Custom',
          description: '',
          isAutoGenerated: false,
        })
        idByName.set(key, id)
      }
    }
    const finalId = idByName.get(finalName.toLowerCase()) ?? null
    if (finalId) set({ model: { ...s.model, tables: tablesCopy }, selectedMeasureId: finalId })
    return finalId
  },

  // ---- plugins ----
  togglePlugins: (open) => set((s) => ({ pluginsOpen: open ?? !s.pluginsOpen })),

  // ---- analyst ----
  toggleAnalyst: (open) => set((s) => ({ analystOpen: open ?? !s.analystOpen })),

  askAnalyst: async (question) => {
    const q = question.trim()
    if (!q) return
    set((s) => ({
      analystOpen: true,
      analystThinking: true,
      analystMessages: [...s.analystMessages, { id: `msg_${msgSeq++}`, role: 'user', text: q }],
    }))
    const { model, datasets } = get()
    const turn = await services.analyst().ask(q, { model, datasets })
    set((s) => ({
      analystThinking: false,
      analystMessages: [
        ...s.analystMessages,
        { id: `msg_${msgSeq++}`, role: 'assistant', text: turn.text, chips: turn.chips },
      ],
    }))
  },
}))
