/**
 * APPLICATION — Exporters (pure)
 * Serialize the model + report to open formats: TMDL, PBIP (file set),
 * Markdown docs, Power BI theme JSON, project JSON, a Tabular Editor C#
 * script, and a self-contained interactive HTML dashboard.
 */
import type { DataType, SemanticModel } from '@/domain/model'
import type { Report, Visual } from '@/domain/report'
import type { DatasetData } from '@/application/import/types'
import type { VisualSpec } from '@/application/insights/dashboard-generator'
import type { MeasureKind } from '@/application/insights/kpi-engine'
import { groupBy, makeCtx, scalar } from '@/application/query/query-engine'
import type { ZipEntry } from '@/infrastructure/export/zip'

// ---- helpers ----
const q = (name: string): string => (/[^A-Za-z0-9_]/.test(name) ? `'${name}'` : name)

const TMDL_TYPE: Record<DataType, string> = {
  string: 'string',
  integer: 'int64',
  decimal: 'double',
  boolean: 'boolean',
  date: 'dateTime',
  dateTime: 'dateTime',
  time: 'dateTime',
}

function fmtNum(v: number, kind: MeasureKind): string {
  if (kind === 'ratio') return `${(v * 100).toFixed(1)}%`
  const a = Math.abs(v)
  const s = a >= 1e9 ? `${(v / 1e9).toFixed(1)}B` : a >= 1e6 ? `${(v / 1e6).toFixed(1)}M` : a >= 1e3 ? `${(v / 1e3).toFixed(1)}K` : `${Math.round(v)}`
  return kind === 'currency' ? `$${s}` : s
}

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

// ---------------------------------------------------------------------------
// TMDL
// ---------------------------------------------------------------------------

export function tableToTMDL(model: SemanticModel, tableId: string): string {
  const t = model.tables.find((x) => x.id === tableId)
  if (!t) return ''
  const lines: string[] = [`table ${q(t.name)}`, '']
  for (const c of t.columns) {
    lines.push(`\tcolumn ${q(c.name)}`)
    lines.push(`\t\tdataType: ${TMDL_TYPE[c.dataType]}`)
    lines.push(`\t\tsummarizeBy: ${c.role === 'measureCandidate' ? 'sum' : 'none'}`)
    lines.push(`\t\tsourceColumn: ${c.name}`)
    if (c.isHidden) lines.push(`\t\tisHidden`)
    lines.push('')
  }
  for (const m of t.measures) {
    lines.push(`\tmeasure ${q(m.name)} = ${m.expression.replace(/\n/g, '\n\t\t')}`)
    if (m.formatString) lines.push(`\t\tformatString: ${m.formatString}`)
    if (m.displayFolder) lines.push(`\t\tdisplayFolder: ${m.displayFolder}`)
    lines.push('')
  }
  return lines.join('\n')
}

export function relationshipsTMDL(model: SemanticModel): string {
  const out: string[] = []
  model.relationships.forEach((r, i) => {
    const from = model.tables.find((t) => t.id === r.fromTable)
    const to = model.tables.find((t) => t.id === r.toTable)
    const fromCol = from?.columns.find((c) => c.id === r.fromColumn)
    const toCol = to?.columns.find((c) => c.id === r.toColumn)
    if (!from || !to || !fromCol || !toCol) return
    out.push(`relationship rel_${i + 1}`)
    out.push(`\tfromColumn: ${q(from.name)}.${q(fromCol.name)}`)
    out.push(`\ttoColumn: ${q(to.name)}.${q(toCol.name)}`)
    if (!r.isActive) out.push(`\tisActive: false`)
    if (r.crossFilter === 'both') out.push(`\tcrossFilteringBehavior: bothDirections`)
    out.push('')
  })
  return out.join('\n')
}

export function toTMDL(model: SemanticModel): string {
  const parts = [`// Model: ${model.name}`, `// Generated by BI Design Studio`, '']
  for (const t of model.tables) parts.push(tableToTMDL(model, t.id), '')
  parts.push(relationshipsTMDL(model))
  return parts.join('\n')
}

// ---------------------------------------------------------------------------
// Markdown documentation
// ---------------------------------------------------------------------------

export function toMarkdown(model: SemanticModel, report: Report): string {
  const md: string[] = [`# ${model.name} — Model Documentation`, '', `_Generated by BI Design Studio._`, '']
  md.push(`## Overview`, '')
  md.push(`- **Tables:** ${model.tables.length}`)
  md.push(`- **Relationships:** ${model.relationships.length}`)
  md.push(`- **Measures:** ${model.tables.reduce((n, t) => n + t.measures.length, 0)}`)
  md.push(`- **Report pages:** ${report.pages.length}`, '')

  for (const t of model.tables) {
    md.push(`## ${t.name} \`${t.role}\``, '')
    md.push(`| Column | Type | Role | Distinct |`, `| --- | --- | --- | --- |`)
    for (const c of t.columns) {
      md.push(`| ${c.name} | ${c.dataType} | ${c.role} | ${c.distinctCount ?? '—'} |`)
    }
    md.push('')
    if (t.measures.length) {
      md.push(`**Measures**`, '')
      for (const m of t.measures) md.push(`- \`${m.name}\` = \`${m.expression.replace(/\n/g, ' ')}\``)
      md.push('')
    }
  }

  if (model.relationships.length) {
    md.push(`## Relationships`, '')
    model.relationships.forEach((r) => {
      const from = model.tables.find((t) => t.id === r.fromTable)
      const to = model.tables.find((t) => t.id === r.toTable)
      const fc = from?.columns.find((c) => c.id === r.fromColumn)
      const tc = to?.columns.find((c) => c.id === r.toColumn)
      if (from && to && fc && tc) md.push(`- ${from.name}[${fc.name}] → ${to.name}[${tc.name}] (${r.fromCardinality}:${r.toCardinality})`)
    })
    md.push('')
  }
  return md.join('\n')
}

// ---------------------------------------------------------------------------
// Power BI theme JSON
// ---------------------------------------------------------------------------

export function toThemeJSON(): string {
  return JSON.stringify(
    {
      name: 'BI Design Studio',
      dataColors: ['#3b6ef6', '#17a673', '#d98a15', '#8b5cf6', '#e5484d', '#0ea5e9', '#ec4899', '#64748b'],
      background: '#FFFFFF',
      foreground: '#17181B',
      tableAccent: '#3b6ef6',
      visualStyles: {
        '*': {
          '*': {
            background: [{ color: { solid: { color: '#FFFFFF' } } }],
            border: [{ color: { solid: { color: '#E8E8EC' } }, radius: 10 }],
          },
        },
      },
    },
    null,
    2,
  )
}

// ---------------------------------------------------------------------------
// Project JSON
// ---------------------------------------------------------------------------

export function toProjectJSON(model: SemanticModel, report: Report): string {
  return JSON.stringify({ version: '1.0', tool: 'BI Design Studio', model, report }, null, 2)
}

// ---------------------------------------------------------------------------
// Tabular Editor C# script
// ---------------------------------------------------------------------------

export function toTabularEditorScript(model: SemanticModel): string {
  const lines: string[] = ['// Tabular Editor C# script — recreates measures', '// Generated by BI Design Studio', '']
  for (const t of model.tables) {
    for (const m of t.measures) {
      const expr = m.expression.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ')
      lines.push(`try {`)
      lines.push(`    var m = Model.Tables["${t.name}"].AddMeasure("${m.name}", "${expr}");`)
      if (m.formatString) lines.push(`    m.FormatString = "${m.formatString.replace(/\\/g, '\\\\')}";`)
      if (m.displayFolder) lines.push(`    m.DisplayFolder = "${m.displayFolder}";`)
      lines.push(`} catch (Exception ex) { Info(ex.Message); }`)
      lines.push('')
    }
  }
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Interactive HTML
// ---------------------------------------------------------------------------

function renderVisualHTML(visual: Visual, ctx: ReturnType<typeof makeCtx>): string {
  const spec = (visual.style as { spec?: VisualSpec } | undefined)?.spec
  if (!spec) return ''
  const title = esc(visual.title ?? '')

  if (spec.type === 'card') {
    const v = scalar(ctx, spec.measure)
    return `<div class="card"><div class="k">${esc(title)}</div><div class="v">${fmtNum(v, spec.measure.kind)}</div></div>`
  }
  const measure = 'measure' in spec ? spec.measure : null
  const category = 'category' in spec ? spec.category : null
  if (!measure || !category) return ''
  const pts = groupBy(ctx, measure, category, { topN: spec.type === 'rank' ? spec.topN : 12 })
  const max = Math.max(...pts.map((p) => p.value), 1)
  const bars = pts
    .map(
      (p) =>
        `<div class="bar"><span class="bl">${esc(p.label)}</span><span class="bt"><span class="bf" style="width:${(p.value / max) * 100}%"></span></span><span class="bv">${fmtNum(p.value, measure.kind)}</span></div>`,
    )
    .join('')
  return `<div class="tile"><div class="t">${title}</div><div class="bars">${bars}</div></div>`
}

export function toInteractiveHTML(model: SemanticModel, report: Report, datasets: DatasetData[]): string {
  const ctx = makeCtx(model, datasets)
  const page = report.pages.find((p) => p.id === report.activePageId) ?? report.pages[0]
  const cards = page?.visuals.filter((v) => v.kind === 'card' || v.kind === 'kpi') ?? []
  const charts = page?.visuals.filter((v) => v.kind !== 'card' && v.kind !== 'kpi' && v.kind !== 'slicer') ?? []
  const cardHTML = cards.map((v) => renderVisualHTML(v, ctx)).join('')
  const chartHTML = charts.map((v) => renderVisualHTML(v, ctx)).join('')

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(page?.name ?? 'Dashboard')} — BI Design Studio</title>
<style>
:root{--bg:#fbfbfd;--surface:#fff;--border:#e8e8ec;--text:#17181b;--muted:#64686f;--accent:#3b6ef6;}
*{box-sizing:border-box;margin:0}body{font-family:Inter,Segoe UI,system-ui,sans-serif;background:var(--bg);color:var(--text);padding:32px}
h1{font-size:26px;margin-bottom:4px}.sub{color:var(--muted);margin-bottom:24px;font-size:14px}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px;margin-bottom:16px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:20px}
.card .k{font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}
.card .v{font-size:30px;font-weight:700;margin-top:6px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px}
.tile{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:16px}
.tile .t{font-size:13px;font-weight:600;color:var(--muted);margin-bottom:12px}
.bar{display:grid;grid-template-columns:120px 1fr 64px;align-items:center;gap:10px;margin:6px 0;font-size:13px}
.bl{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--muted)}
.bt{height:16px;background:#f0f1f4;border-radius:4px;overflow:hidden}
.bf{display:block;height:100%;background:var(--accent);border-radius:4px}
.bv{text-align:right;font-weight:600;font-variant-numeric:tabular-nums}
footer{margin-top:32px;color:var(--muted);font-size:12px}
</style></head><body>
<h1>${esc(page?.name ?? 'Dashboard')}</h1><div class="sub">Exported from BI Design Studio · ${model.tables.length} tables</div>
<div class="cards">${cardHTML}</div>
<div class="grid">${chartHTML}</div>
<footer>Generated by BI Design Studio — offline, open-format export.</footer>
</body></html>`
}

// ---------------------------------------------------------------------------
// PBIP file set (bundled into a ZIP)
// ---------------------------------------------------------------------------

export function buildPBIP(model: SemanticModel, report: Report, name: string): ZipEntry[] {
  const safe = name.replace(/[^A-Za-z0-9_-]+/g, '_') || 'project'
  const entries: ZipEntry[] = []

  entries.push({
    path: `${safe}.pbip`,
    content: JSON.stringify(
      { version: '1.0', artifacts: [{ report: { path: `${safe}.Report` } }], settings: { enableAutoRecovery: true } },
      null,
      2,
    ),
  })

  // Semantic model (TMDL)
  entries.push({
    path: `${safe}.SemanticModel/definition/model.tmdl`,
    content: `model Model\n\tculture: en-US\n\ndefaultPowerBIDataSourceVersion: powerBI_V3\n`,
  })
  for (const t of model.tables) {
    entries.push({ path: `${safe}.SemanticModel/definition/tables/${t.name}.tmdl`, content: tableToTMDL(model, t.id) })
  }
  entries.push({ path: `${safe}.SemanticModel/definition/relationships.tmdl`, content: relationshipsTMDL(model) })
  entries.push({
    path: `${safe}.SemanticModel/definition.pbism`,
    content: JSON.stringify({ version: '4.0', settings: {} }, null, 2),
  })

  // Report
  entries.push({ path: `${safe}.Report/report.json`, content: toProjectJSON(model, report) })
  entries.push({ path: `${safe}.Report/definition.pbir`, content: JSON.stringify({ version: '1.0', datasetReference: { byPath: { path: `../${safe}.SemanticModel` } } }, null, 2) })

  // Docs + theme
  entries.push({ path: `${safe}.Report/StaticResources/theme.json`, content: toThemeJSON() })
  entries.push({ path: `README.md`, content: toMarkdown(model, report) })

  return entries
}
